package codegen

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	oapicodegen "github.com/oapi-codegen/oapi-codegen/v2/pkg/codegen"
	"gopkg.in/yaml.v3"
)

// pointerTypeRe finds struct fields with pointer-to-named-type discriminators:
//
//	Type *TrackObjectType `json:"type,omitempty"`
var pointerTypeRe = regexp.MustCompile(`\w+ \*(\w+Type)\s+` + "`")

// assignRe matches discriminator assignments: v.Type = "TrackObject"
var assignRe = regexp.MustCompile(`(\w+)\.(\w+) = ("(\w+)")`)

// fixDiscriminatorAssignments rewrites broken discriminator const assignments
// generated by oapi-codegen. Only assignments where the target field is a
// pointer-to-named-type (identified from struct definitions) are rewritten.
// Non-pointer fields that accept string constants are left unchanged.
func fixDiscriminatorAssignments(code string) string {
	// Collect the set of pointer discriminator type names
	pointerTypes := make(map[string]bool)
	for _, match := range pointerTypeRe.FindAllStringSubmatch(code, -1) {
		pointerTypes[match[1]] = true // e.g., "TrackObjectType"
	}

	return assignRe.ReplaceAllStringFunc(code, func(match string) string {
		parts := assignRe.FindStringSubmatch(match)
		if len(parts) < 5 {
			return match
		}
		varName, field, value := parts[1], parts[2], parts[4]
		typeName := value + field // e.g., "TrackObject" + "Type" = "TrackObjectType"
		if !pointerTypes[typeName] {
			return match // not a pointer field, leave unchanged
		}
		return fmt.Sprintf("__disc_%s := %s(%q); %s.%s = &__disc_%s",
			value, typeName, value, varName, field, value)
	})
}

// GenerateConfig holds the configuration for oapi-codegen generation.
type GenerateConfig struct {
	PackageName  string
	ClientOutput string
	TypesOutput  string
	SkipPrune    bool
}

// LoadOapiCodegenConfig reads an oapi-codegen YAML config file and returns
// the settings relevant to generation. The client output path comes from the
// config's "output" field. The types output path is derived by replacing
// "_client.go" with "_types.go".
func LoadOapiCodegenConfig(path string) (*GenerateConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading oapi-codegen config: %w", err)
	}

	var raw struct {
		Package       string `yaml:"package"`
		Output        string `yaml:"output"`
		OutputOptions struct {
			SkipPrune bool `yaml:"skip-prune"`
		} `yaml:"output-options"`
	}
	if err := yaml.Unmarshal(data, &raw); err != nil {
		return nil, fmt.Errorf("parsing oapi-codegen config: %w", err)
	}

	clientOutput := raw.Output
	typesOutput := strings.Replace(clientOutput, "_client.go", "_types.go", 1)

	return &GenerateConfig{
		PackageName:  raw.Package,
		ClientOutput: clientOutput,
		TypesOutput:  typesOutput,
		SkipPrune:    raw.OutputOptions.SkipPrune,
	}, nil
}

// GenerateFromSpec generates Go client and types files from an OpenAPI spec.
// It filters out deprecated operations before passing the spec to oapi-codegen.
func GenerateFromSpec(specData []byte, config *GenerateConfig) error {
	sanitized, err := SanitizeSpec(specData)
	if err != nil {
		return fmt.Errorf("sanitizing spec: %w", err)
	}

	loader := openapi3.NewLoader()
	doc, err := loader.LoadFromData(sanitized)
	if err != nil {
		return fmt.Errorf("loading OpenAPI spec: %w", err)
	}

	filterDeprecated(doc)

	clientCode, err := generateCode(doc, config.PackageName, config.SkipPrune, true, false)
	if err != nil {
		return fmt.Errorf("generating client code: %w", err)
	}

	typesCode, err := generateCode(doc, config.PackageName, config.SkipPrune, false, true)
	if err != nil {
		return fmt.Errorf("generating types code: %w", err)
	}

	// Fix oapi-codegen discriminator bug: it generates `v.Type = "FooObject"`
	// where Type is *FooObjectType (a pointer to a named string type). The fix
	// converts these to proper pointer assignments.
	typesCode = fixDiscriminatorAssignments(typesCode)

	if err := writeFile(config.ClientOutput, clientCode); err != nil {
		return fmt.Errorf("writing client file: %w", err)
	}
	if err := writeFile(config.TypesOutput, typesCode); err != nil {
		return fmt.Errorf("writing types file: %w", err)
	}

	return nil
}

func generateCode(doc *openapi3.T, pkg string, skipPrune, client, models bool) (string, error) {
	cfg := oapicodegen.Configuration{
		PackageName: pkg,
		Generate: oapicodegen.GenerateOptions{
			Client: client,
			Models: models,
		},
		OutputOptions: oapicodegen.OutputOptions{
			SkipPrune: skipPrune,
		},
	}
	code, err := oapicodegen.Generate(doc, cfg)
	if err != nil {
		return "", err
	}
	return code, nil
}

func filterDeprecated(doc *openapi3.T) {
	if doc.Paths == nil {
		return
	}

	var toDelete []string

	for path, item := range doc.Paths.Map() {
		if item.Get != nil && item.Get.Deprecated {
			item.Get = nil
		}
		if item.Put != nil && item.Put.Deprecated {
			item.Put = nil
		}
		if item.Post != nil && item.Post.Deprecated {
			item.Post = nil
		}
		if item.Delete != nil && item.Delete.Deprecated {
			item.Delete = nil
		}
		if item.Patch != nil && item.Patch.Deprecated {
			item.Patch = nil
		}

		if item.Get == nil && item.Put == nil && item.Post == nil &&
			item.Delete == nil && item.Patch == nil {
			toDelete = append(toDelete, path)
		}
	}

	for _, path := range toDelete {
		doc.Paths.Delete(path)
	}
}

func writeFile(path, content string) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0644)
}
