package codegen

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

// GenerateToolsFile generates and writes the MCP tools Go source file.
func GenerateToolsFile(ops []Operation, packageName, outputPath string) error {
	code, err := GenerateTools(ops, packageName)
	if err != nil {
		return err
	}
	dir := filepath.Dir(outputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}
	return os.WriteFile(outputPath, []byte(code), 0644)
}

// GenerateTools generates MCP tool definitions Go source code from parsed operations.
// Operations are sorted by operationID for deterministic output.
func GenerateTools(ops []Operation, packageName string) (string, error) {
	sorted := make([]Operation, len(ops))
	copy(sorted, ops)
	sort.Slice(sorted, func(i, j int) bool {
		return sorted[i].OperationID < sorted[j].OperationID
	})

	data := toolsTemplateData{
		PackageName: packageName,
	}
	for _, op := range sorted {
		data.Tools = append(data.Tools, newToolData(op))
	}

	tmpl, err := template.New("tools").Funcs(template.FuncMap{
		"quote": func(s string) string { return fmt.Sprintf("%q", s) },
	}).Parse(toolsTmpl)
	if err != nil {
		return "", fmt.Errorf("parsing template: %w", err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("executing template: %w", err)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return "", fmt.Errorf("formatting generated code: %w\n%s", err, buf.String())
	}
	return string(formatted), nil
}

type toolsTemplateData struct {
	PackageName string
	Tools       []toolData
}

type toolData struct {
	OperationID string
	VarName     string
	HandlerName string
	Description string
	Scopes      []string
	Method      string
	PathPattern string
	HasBody     bool
	Params      []toolParamData
	PathParams  []toolParamData
	QueryParams []toolParamData
}

type toolParamData struct {
	Name        string
	MCPType     string
	Required    bool
	Description string
}

func newToolData(op Operation) toolData {
	camel := kebabToCamel(op.OperationID)
	td := toolData{
		OperationID: op.OperationID,
		VarName:     camel + "Tool",
		HandlerName: "New" + camel + "Handler",
		Description: toolDescription(op.Summary, op.Description),
		Scopes:      op.Scopes,
		Method:      op.Method,
		PathPattern: op.Path,
		HasBody:     op.RequestBodyRef != "",
	}

	for _, p := range op.Parameters {
		pd := toolParamData{
			Name:        p.Name,
			MCPType:     mcpType(p.Type),
			Required:    p.Required,
			Description: p.Description,
		}
		td.Params = append(td.Params, pd)
		switch p.In {
		case "path":
			td.PathParams = append(td.PathParams, pd)
		case "query":
			td.QueryParams = append(td.QueryParams, pd)
		}
	}

	return td
}

func kebabToCamel(s string) string {
	parts := strings.Split(s, "-")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}

func toolDescription(summary, description string) string {
	if summary != "" && description != "" {
		return summary + "\n\n" + description
	}
	if summary != "" {
		return summary
	}
	return description
}

func mcpType(openAPIType string) string {
	switch openAPIType {
	case "integer", "number":
		return "Number"
	case "boolean":
		return "Boolean"
	case "array":
		return "Array"
	default:
		return "String"
	}
}

const toolsTmpl = `// Code generated by cmd/codegen; DO NOT EDIT.

package {{.PackageName}}

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
)

const spotifyAPIBase = "https://api.spotify.com"

{{- range .Tools}}

// {{.VarName}}Scopes lists the OAuth scopes required by the {{.OperationID}} tool.
var {{.VarName}}Scopes = []string{ {{- range .Scopes}}{{quote .}}, {{end -}} }

var {{.VarName}} = mcp.NewTool({{quote .OperationID}},
	mcp.WithDescription({{quote .Description}}),
{{- range .Params}}
	mcp.With{{.MCPType}}({{quote .Name}}{{if .Required}}, mcp.Required(){{end}}{{if .Description}}, mcp.Description({{quote .Description}}){{end}}),
{{- end}}
)

// {{.HandlerName}} creates a handler for the {{.OperationID}} tool.
func {{.HandlerName}}(httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := {{quote .PathPattern}}
{{- range .PathParams}}
		path = strings.ReplaceAll(path, "{ {{- .Name -}} }", req.GetString({{quote .Name}}, ""))
{{- end}}

		httpReq, err := http.NewRequestWithContext(ctx, {{quote .Method}}, spotifyAPIBase+path, {{if .HasBody}}strings.NewReader(req.GetString("body", "{}")){{else}}nil{{end}})
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
{{- if .HasBody}}
		httpReq.Header.Set("Content-Type", "application/json")
{{- end}}
{{- if .QueryParams}}

		q := httpReq.URL.Query()
{{- range .QueryParams}}
		if v := req.GetString({{quote .Name}}, ""); v != "" {
			q.Set({{quote .Name}}, v)
		}
{{- end}}
		httpReq.URL.RawQuery = q.Encode()
{{- end}}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}
{{end}}

// AllTools contains all generated MCP tool definitions.
var AllTools = []mcp.Tool{
{{- range .Tools}}
	{{.VarName}},
{{- end}}
}
`
