// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// AddItemsToPlaylistToolScopes lists the OAuth scopes required by the add-items-to-playlist tool.
var AddItemsToPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var AddItemsToPlaylistTool = mcp.NewTool("add-items-to-playlist",
	mcp.WithDescription("Add Items to Playlist\n\n\nAdd one or more items to a user's playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithNumber("position", mcp.Description("The position to insert the items, a zero-based index. For example, to insert the items in the first position: `position=0` ; to insert the items in the third position: `position=2`. If omitted, the items will be appended to the playlist. Items are added in the order they appear in the uris array. For example: `{\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\"], \"position\": 3}`\n")),
	mcp.WithArray("uris", mcp.Description("A JSON array of the [Spotify URIs](/documentation/web-api/concepts/spotify-uris-ids) to add. For example: `{\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\", \"spotify:episode:512ojhOuo1ktJprKbVcKyQ\"]}`<br/>A maximum of 100 items can be added in one request. _**Note**: if the `uris` parameter is present in the query string, any URIs listed here in the body will be ignored._\n")),
)

// NewAddItemsToPlaylistHandler creates a handler for the add-items-to-playlist tool.
func NewAddItemsToPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		params := &spotify.AddItemsToPlaylistParams{}
		var body spotify.AddItemsToPlaylistJSONRequestBody
		if v, ok := args["position"]; ok {
			n := toInt(v)
			body.Position = &n
		}
		if v, ok := args["uris"]; ok {
			sl := toStringSlice(v)
			body.Uris = &sl
		}
		resp, err := client.AddItemsToPlaylistWithResponse(ctx, playlistId, params, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
