// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetUsersSavedAudiobooksToolScopes lists the OAuth scopes required by the get-users-saved-audiobooks tool.
var GetUsersSavedAudiobooksToolScopes = []string{"user-library-read"}

var GetUsersSavedAudiobooksTool = mcp.NewTool("get-users-saved-audiobooks",
	mcp.WithDescription("Get User's Saved Audiobooks\n\n\nGet a list of the audiobooks saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedAudiobooksHandler creates a handler for the get-users-saved-audiobooks tool.
func NewGetUsersSavedAudiobooksHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetUsersSavedAudiobooksParams{}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetUsersSavedAudiobooksWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
