// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetCurrentUsersProfileToolScopes lists the OAuth scopes required by the get-current-users-profile tool.
var GetCurrentUsersProfileToolScopes = []string{"user-read-private", "user-read-email"}

var GetCurrentUsersProfileTool = mcp.NewTool("get-current-users-profile",
	mcp.WithDescription("Get Current User's Profile\n\n\nGet detailed profile information about the current user (including the\ncurrent user's username).\n"),
)

// NewGetCurrentUsersProfileHandler creates a handler for the get-current-users-profile tool.
func NewGetCurrentUsersProfileHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		resp, err := client.GetCurrentUsersProfileWithResponse(ctx)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
