// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// RemoveItemsPlaylistToolScopes lists the OAuth scopes required by the remove-items-playlist tool.
var RemoveItemsPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var RemoveItemsPlaylistTool = mcp.NewTool("remove-items-playlist",
	mcp.WithDescription("Remove Playlist Items\n\n\nRemove one or more items from a user's playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
)

// NewRemoveItemsPlaylistHandler creates a handler for the remove-items-playlist tool.
func NewRemoveItemsPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		var body spotify.RemoveItemsPlaylistJSONRequestBody
		resp, err := client.RemoveItemsPlaylistWithResponse(ctx, playlistId, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
