// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetPlaylistsItemsToolScopes lists the OAuth scopes required by the get-playlists-items tool.
var GetPlaylistsItemsToolScopes = []string{"playlist-read-private"}

var GetPlaylistsItemsTool = mcp.NewTool("get-playlists-items",
	mcp.WithDescription("Get Playlist Items\n\n\nGet full details of the items of a playlist owned by a Spotify user.\n\n**Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithString("fields"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
	mcp.WithString("additional_types"),
)

// NewGetPlaylistsItemsHandler creates a handler for the get-playlists-items tool.
func NewGetPlaylistsItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		params := &spotify.GetPlaylistsItemsParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["fields"].(string); ok && v != "" {
			params.Fields = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		if v, ok := args["additional_types"].(string); ok && v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetPlaylistsItemsWithResponse(ctx, playlistId, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
