// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAudiobookChaptersToolScopes lists the OAuth scopes required by the get-audiobook-chapters tool.
var GetAudiobookChaptersToolScopes = []string{}

var GetAudiobookChaptersTool = mcp.NewTool("get-audiobook-chapters",
	mcp.WithDescription("Get Audiobook Chapters\n\n\nGet Spotify catalog information about an audiobook's chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAudiobookChaptersHandler creates a handler for the get-audiobook-chapters tool.
func NewGetAudiobookChaptersHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		params := &spotify.GetAudiobookChaptersParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetAudiobookChaptersWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
