// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetUsersTopArtistsAndTracksToolScopes lists the OAuth scopes required by the get-users-top-artists-and-tracks tool.
var GetUsersTopArtistsAndTracksToolScopes = []string{"user-top-read"}

var GetUsersTopArtistsAndTracksTool = mcp.NewTool("get-users-top-artists-and-tracks",
	mcp.WithDescription("Get User's Top Items\n\n\nGet the current user's top artists or tracks based on calculated affinity.\n"),
	mcp.WithString("type", mcp.Required()),
	mcp.WithString("time_range"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersTopArtistsAndTracksHandler creates a handler for the get-users-top-artists-and-tracks tool.
func NewGetUsersTopArtistsAndTracksHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		pType, _ := args["type"].(string)
		params := &spotify.GetUsersTopArtistsAndTracksParams{}
		if v, ok := args["time_range"].(string); ok && v != "" {
			params.TimeRange = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetUsersTopArtistsAndTracksWithResponse(ctx, spotify.GetUsersTopArtistsAndTracksParamsType(pType), params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
