// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAShowToolScopes lists the OAuth scopes required by the get-a-show tool.
var GetAShowToolScopes = []string{"user-read-playback-position"}

var GetAShowTool = mcp.NewTool("get-a-show",
	mcp.WithDescription("Get Show\n\n\nGet Spotify catalog information for a single show identified by its\nunique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAShowHandler creates a handler for the get-a-show tool.
func NewGetAShowHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		params := &spotify.GetAShowParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		resp, err := client.GetAShowWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
