// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// CreatePlaylistToolScopes lists the OAuth scopes required by the create-playlist tool.
var CreatePlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var CreatePlaylistTool = mcp.NewTool("create-playlist",
	mcp.WithDescription("Create Playlist\n\n\nCreate a playlist for the current Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n"),
	mcp.WithBoolean("collaborative", mcp.Description("Defaults to `false`. If `true` the playlist will be collaborative. _**Note**: to create a collaborative playlist you must also set `public` to `false`. To create collaborative playlists you must have granted `playlist-modify-private` and `playlist-modify-public` [scopes](/documentation/web-api/concepts/scopes/#list-of-scopes)._\n")),
	mcp.WithString("description", mcp.Description("value for playlist description as displayed in Spotify Clients and in the Web API.\n")),
	mcp.WithString("name", mcp.Required(), mcp.Description("The name for the new playlist, for example `\"Your Coolest Playlist\"`. This name does not need to be unique; a user may have several playlists with the same name.\n")),
	mcp.WithBoolean("public", mcp.Description("Defaults to `true`. The playlist's public/private status (if it should be added to the user's profile or not): `true` the playlist will be public, `false` the playlist will be private. To be able to create private playlists, the user must have granted the `playlist-modify-private` [scope](/documentation/web-api/concepts/scopes/#list-of-scopes). For more about public/private status, see [Working with Playlists](/documentation/web-api/concepts/playlists)\n")),
)

// NewCreatePlaylistHandler creates a handler for the create-playlist tool.
func NewCreatePlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		var body spotify.CreatePlaylistJSONRequestBody
		if v, ok := args["collaborative"]; ok {
			b := toBool(v)
			body.Collaborative = &b
		}
		if v, ok := args["description"].(string); ok && v != "" {
			body.Description = &v
		}
		if v, ok := args["name"].(string); ok {
			body.Name = v
		}
		if v, ok := args["public"]; ok {
			b := toBool(v)
			body.Public = &b
		}
		resp, err := client.CreatePlaylistWithResponse(ctx, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
