// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetQueueToolScopes lists the OAuth scopes required by the get-queue tool.
var GetQueueToolScopes = []string{"user-read-currently-playing", "user-read-playback-state"}

var GetQueueTool = mcp.NewTool("get-queue",
	mcp.WithDescription("Get the User's Queue\n\n\nGet the list of objects that make up the user's queue.\n"),
)

// NewGetQueueHandler creates a handler for the get-queue tool.
func NewGetQueueHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		resp, err := client.GetQueueWithResponse(ctx)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
