// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// SearchToolScopes lists the OAuth scopes required by the search tool.
var SearchToolScopes = []string{}

var SearchTool = mcp.NewTool("search",
	mcp.WithDescription("Search for Item\n\n\nGet Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks\nthat match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("q", mcp.Required()),
	mcp.WithArray("type", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
	mcp.WithString("include_external"),
)

// NewSearchHandler creates a handler for the search tool.
func NewSearchHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.SearchParams{}
		params.Q = args["q"].(string)
		if v, ok := args["type"]; ok {
			params.Type = toTypedSlice[spotify.SearchParamsType](v)
		}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		if v, ok := args["include_external"].(string); ok && v != "" {
			ev := spotify.SearchParamsIncludeExternal(v)
			params.IncludeExternal = &ev
		}
		resp, err := client.SearchWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
