// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"
	"io"
	"net/http"
	"strings"

	"github.com/mark3labs/mcp-go/mcp"
)

// AddItemsToPlaylistToolScopes lists the OAuth scopes required by the add-items-to-playlist tool.
var AddItemsToPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var AddItemsToPlaylistTool = mcp.NewTool("add-items-to-playlist",
	mcp.WithDescription("Add Items to Playlist\n\n\nAdd one or more items to a user's playlist.\n"),
	mcp.WithString(""),
	mcp.WithNumber("position"),
	mcp.WithString("uris"),
)

// NewAddItemsToPlaylistHandler creates a handler for the add-items-to-playlist tool.
func NewAddItemsToPlaylistHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}/items"

		httpReq, err := http.NewRequestWithContext(ctx, "POST", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("position", ""); v != "" {
			q.Set("position", v)
		}
		if v := req.GetString("uris", ""); v != "" {
			q.Set("uris", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// AddToQueueToolScopes lists the OAuth scopes required by the add-to-queue tool.
var AddToQueueToolScopes = []string{"user-modify-playback-state"}

var AddToQueueTool = mcp.NewTool("add-to-queue",
	mcp.WithDescription("Add Item to Playback Queue\n\n\nAdd an item to be played next in the user's current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("uri", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewAddToQueueHandler creates a handler for the add-to-queue tool.
func NewAddToQueueHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/queue"

		httpReq, err := http.NewRequestWithContext(ctx, "POST", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("uri", ""); v != "" {
			q.Set("uri", v)
		}
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// ChangePlaylistDetailsToolScopes lists the OAuth scopes required by the change-playlist-details tool.
var ChangePlaylistDetailsToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var ChangePlaylistDetailsTool = mcp.NewTool("change-playlist-details",
	mcp.WithDescription("Change Playlist Details\n\n\nChange a playlist's name and public/private state. (The user must, of\ncourse, own the playlist.)\n"),
	mcp.WithString(""),
)

// NewChangePlaylistDetailsHandler creates a handler for the change-playlist-details tool.
func NewChangePlaylistDetailsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// CheckLibraryContainsToolScopes lists the OAuth scopes required by the check-library-contains tool.
var CheckLibraryContainsToolScopes = []string{"user-library-read", "user-follow-read", "playlist-read-private"}

var CheckLibraryContainsTool = mcp.NewTool("check-library-contains",
	mcp.WithDescription("Check User's Saved Items\n\n\nCheck if one or more items are already saved in the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewCheckLibraryContainsHandler creates a handler for the check-library-contains tool.
func NewCheckLibraryContainsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/library/contains"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("uris", ""); v != "" {
			q.Set("uris", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// CreatePlaylistToolScopes lists the OAuth scopes required by the create-playlist tool.
var CreatePlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var CreatePlaylistTool = mcp.NewTool("create-playlist",
	mcp.WithDescription("Create Playlist\n\n\nCreate a playlist for the current Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n"),
)

// NewCreatePlaylistHandler creates a handler for the create-playlist tool.
func NewCreatePlaylistHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/playlists"

		httpReq, err := http.NewRequestWithContext(ctx, "POST", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAChapterToolScopes lists the OAuth scopes required by the get-a-chapter tool.
var GetAChapterToolScopes = []string{}

var GetAChapterTool = mcp.NewTool("get-a-chapter",
	mcp.WithDescription("Get a Chapter\n\n\nGet Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAChapterHandler creates a handler for the get-a-chapter tool.
func NewGetAChapterHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/chapters/{id}"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAListOfCurrentUsersPlaylistsToolScopes lists the OAuth scopes required by the get-a-list-of-current-users-playlists tool.
var GetAListOfCurrentUsersPlaylistsToolScopes = []string{"playlist-read-private"}

var GetAListOfCurrentUsersPlaylistsTool = mcp.NewTool("get-a-list-of-current-users-playlists",
	mcp.WithDescription("Get Current User's Playlists\n\n\nGet a list of the playlists owned or followed by the current Spotify\nuser.\n"),
	mcp.WithString(""),
	mcp.WithNumber("offset"),
)

// NewGetAListOfCurrentUsersPlaylistsHandler creates a handler for the get-a-list-of-current-users-playlists tool.
func NewGetAListOfCurrentUsersPlaylistsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/playlists"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("offset", ""); v != "" {
			q.Set("offset", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAShowToolScopes lists the OAuth scopes required by the get-a-show tool.
var GetAShowToolScopes = []string{"user-read-playback-position"}

var GetAShowTool = mcp.NewTool("get-a-show",
	mcp.WithDescription("Get Show\n\n\nGet Spotify catalog information for a single show identified by its\nunique Spotify ID.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAShowHandler creates a handler for the get-a-show tool.
func NewGetAShowHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/shows/{id}"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAShowsEpisodesToolScopes lists the OAuth scopes required by the get-a-shows-episodes tool.
var GetAShowsEpisodesToolScopes = []string{"user-read-playback-position"}

var GetAShowsEpisodesTool = mcp.NewTool("get-a-shows-episodes",
	mcp.WithDescription("Get Show Episodes\n\n\nGet Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAShowsEpisodesHandler creates a handler for the get-a-shows-episodes tool.
func NewGetAShowsEpisodesHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/shows/{id}/episodes"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAUsersAvailableDevicesToolScopes lists the OAuth scopes required by the get-a-users-available-devices tool.
var GetAUsersAvailableDevicesToolScopes = []string{"user-read-playback-state"}

var GetAUsersAvailableDevicesTool = mcp.NewTool("get-a-users-available-devices",
	mcp.WithDescription("Get Available Devices\n\n\nGet information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.\n"),
)

// NewGetAUsersAvailableDevicesHandler creates a handler for the get-a-users-available-devices tool.
func NewGetAUsersAvailableDevicesHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/devices"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAnAlbumToolScopes lists the OAuth scopes required by the get-an-album tool.
var GetAnAlbumToolScopes = []string{}

var GetAnAlbumTool = mcp.NewTool("get-an-album",
	mcp.WithDescription("Get Album\n\n\nGet Spotify catalog information for a single album.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAnAlbumHandler creates a handler for the get-an-album tool.
func NewGetAnAlbumHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/albums/{id}"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAnAlbumsTracksToolScopes lists the OAuth scopes required by the get-an-albums-tracks tool.
var GetAnAlbumsTracksToolScopes = []string{}

var GetAnAlbumsTracksTool = mcp.NewTool("get-an-albums-tracks",
	mcp.WithDescription("Get Album Tracks\n\n\nGet Spotify catalog information about an album’s tracks.\nOptional parameters can be used to limit the number of tracks returned.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAnAlbumsTracksHandler creates a handler for the get-an-albums-tracks tool.
func NewGetAnAlbumsTracksHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/albums/{id}/tracks"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAnArtistToolScopes lists the OAuth scopes required by the get-an-artist tool.
var GetAnArtistToolScopes = []string{}

var GetAnArtistTool = mcp.NewTool("get-an-artist",
	mcp.WithDescription("Get Artist\n\n\nGet Spotify catalog information for a single artist identified by their unique Spotify ID.\n"),
	mcp.WithString(""),
)

// NewGetAnArtistHandler creates a handler for the get-an-artist tool.
func NewGetAnArtistHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/artists/{id}"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAnArtistsAlbumsToolScopes lists the OAuth scopes required by the get-an-artists-albums tool.
var GetAnArtistsAlbumsToolScopes = []string{}

var GetAnArtistsAlbumsTool = mcp.NewTool("get-an-artists-albums",
	mcp.WithDescription("Get Artist's Albums\n\n\nGet Spotify catalog information about an artist's albums.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithNumber("limit"),
	mcp.WithString(""),
)

// NewGetAnArtistsAlbumsHandler creates a handler for the get-an-artists-albums tool.
func NewGetAnArtistsAlbumsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/artists/{id}/albums"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("limit", ""); v != "" {
			q.Set("limit", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAnAudiobookToolScopes lists the OAuth scopes required by the get-an-audiobook tool.
var GetAnAudiobookToolScopes = []string{}

var GetAnAudiobookTool = mcp.NewTool("get-an-audiobook",
	mcp.WithDescription("Get an Audiobook\n\n\nGet Spotify catalog information for a single audiobook. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAnAudiobookHandler creates a handler for the get-an-audiobook tool.
func NewGetAnAudiobookHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/audiobooks/{id}"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAnEpisodeToolScopes lists the OAuth scopes required by the get-an-episode tool.
var GetAnEpisodeToolScopes = []string{"user-read-playback-position"}

var GetAnEpisodeTool = mcp.NewTool("get-an-episode",
	mcp.WithDescription("Get Episode\n\n\nGet Spotify catalog information for a single episode identified by its\nunique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString(""),
)

// NewGetAnEpisodeHandler creates a handler for the get-an-episode tool.
func NewGetAnEpisodeHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/episodes/{id}"
		path = strings.ReplaceAll(path, "{id}", req.GetString("id", ""))

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetAudiobookChaptersToolScopes lists the OAuth scopes required by the get-audiobook-chapters tool.
var GetAudiobookChaptersToolScopes = []string{}

var GetAudiobookChaptersTool = mcp.NewTool("get-audiobook-chapters",
	mcp.WithDescription("Get Audiobook Chapters\n\n\nGet Spotify catalog information about an audiobook's chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetAudiobookChaptersHandler creates a handler for the get-audiobook-chapters tool.
func NewGetAudiobookChaptersHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/audiobooks/{id}/chapters"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetCurrentUsersProfileToolScopes lists the OAuth scopes required by the get-current-users-profile tool.
var GetCurrentUsersProfileToolScopes = []string{"user-read-private", "user-read-email"}

var GetCurrentUsersProfileTool = mcp.NewTool("get-current-users-profile",
	mcp.WithDescription("Get Current User's Profile\n\n\nGet detailed profile information about the current user (including the\ncurrent user's username).\n"),
)

// NewGetCurrentUsersProfileHandler creates a handler for the get-current-users-profile tool.
func NewGetCurrentUsersProfileHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetFollowedToolScopes lists the OAuth scopes required by the get-followed tool.
var GetFollowedToolScopes = []string{"user-follow-read"}

var GetFollowedTool = mcp.NewTool("get-followed",
	mcp.WithDescription("Get Followed Artists\n\n\nGet the current user's followed artists.\n"),
	mcp.WithString("type", mcp.Required()),
	mcp.WithString("after"),
	mcp.WithNumber("limit"),
)

// NewGetFollowedHandler creates a handler for the get-followed tool.
func NewGetFollowedHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/following"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("type", ""); v != "" {
			q.Set("type", v)
		}
		if v := req.GetString("after", ""); v != "" {
			q.Set("after", v)
		}
		if v := req.GetString("limit", ""); v != "" {
			q.Set("limit", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetInformationAboutTheUsersCurrentPlaybackToolScopes lists the OAuth scopes required by the get-information-about-the-users-current-playback tool.
var GetInformationAboutTheUsersCurrentPlaybackToolScopes = []string{"user-read-playback-state"}

var GetInformationAboutTheUsersCurrentPlaybackTool = mcp.NewTool("get-information-about-the-users-current-playback",
	mcp.WithDescription("Get Playback State\n\n\nGet information about the user’s current playback state, including track or episode, progress, and active device.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetInformationAboutTheUsersCurrentPlaybackHandler creates a handler for the get-information-about-the-users-current-playback tool.
func NewGetInformationAboutTheUsersCurrentPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetPlaylistToolScopes lists the OAuth scopes required by the get-playlist tool.
var GetPlaylistToolScopes = []string{}

var GetPlaylistTool = mcp.NewTool("get-playlist",
	mcp.WithDescription("Get Playlist\n\n\nGet a playlist owned by a Spotify user.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString("fields"),
	mcp.WithString(""),
)

// NewGetPlaylistHandler creates a handler for the get-playlist tool.
func NewGetPlaylistHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("fields", ""); v != "" {
			q.Set("fields", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetPlaylistCoverToolScopes lists the OAuth scopes required by the get-playlist-cover tool.
var GetPlaylistCoverToolScopes = []string{}

var GetPlaylistCoverTool = mcp.NewTool("get-playlist-cover",
	mcp.WithDescription("Get Playlist Cover Image\n\n\nGet the current image associated with a specific playlist.\n"),
	mcp.WithString(""),
)

// NewGetPlaylistCoverHandler creates a handler for the get-playlist-cover tool.
func NewGetPlaylistCoverHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}/images"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetPlaylistsItemsToolScopes lists the OAuth scopes required by the get-playlists-items tool.
var GetPlaylistsItemsToolScopes = []string{"playlist-read-private"}

var GetPlaylistsItemsTool = mcp.NewTool("get-playlists-items",
	mcp.WithDescription("Get Playlist Items\n\n\nGet full details of the items of a playlist owned by a Spotify user.\n\n**Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString("fields"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetPlaylistsItemsHandler creates a handler for the get-playlists-items tool.
func NewGetPlaylistsItemsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}/items"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("fields", ""); v != "" {
			q.Set("fields", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetQueueToolScopes lists the OAuth scopes required by the get-queue tool.
var GetQueueToolScopes = []string{"user-read-currently-playing", "user-read-playback-state"}

var GetQueueTool = mcp.NewTool("get-queue",
	mcp.WithDescription("Get the User's Queue\n\n\nGet the list of objects that make up the user's queue.\n"),
)

// NewGetQueueHandler creates a handler for the get-queue tool.
func NewGetQueueHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/queue"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetRecentlyPlayedToolScopes lists the OAuth scopes required by the get-recently-played tool.
var GetRecentlyPlayedToolScopes = []string{"user-read-recently-played"}

var GetRecentlyPlayedTool = mcp.NewTool("get-recently-played",
	mcp.WithDescription("Get Recently Played Tracks\n\n\nGet tracks from the current user's recently played tracks.\n_**Note**: Currently doesn't support podcast episodes._\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("after"),
	mcp.WithNumber("before"),
)

// NewGetRecentlyPlayedHandler creates a handler for the get-recently-played tool.
func NewGetRecentlyPlayedHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/recently-played"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("limit", ""); v != "" {
			q.Set("limit", v)
		}
		if v := req.GetString("after", ""); v != "" {
			q.Set("after", v)
		}
		if v := req.GetString("before", ""); v != "" {
			q.Set("before", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetTheUsersCurrentlyPlayingTrackToolScopes lists the OAuth scopes required by the get-the-users-currently-playing-track tool.
var GetTheUsersCurrentlyPlayingTrackToolScopes = []string{"user-read-currently-playing"}

var GetTheUsersCurrentlyPlayingTrackTool = mcp.NewTool("get-the-users-currently-playing-track",
	mcp.WithDescription("Get Currently Playing Track\n\n\nGet the object currently being played on the user's Spotify account.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetTheUsersCurrentlyPlayingTrackHandler creates a handler for the get-the-users-currently-playing-track tool.
func NewGetTheUsersCurrentlyPlayingTrackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/currently-playing"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetTrackToolScopes lists the OAuth scopes required by the get-track tool.
var GetTrackToolScopes = []string{}

var GetTrackTool = mcp.NewTool("get-track",
	mcp.WithDescription("Get Track\n\n\nGet Spotify catalog information for a single track identified by its\nunique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString(""),
)

// NewGetTrackHandler creates a handler for the get-track tool.
func NewGetTrackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/tracks/{id}"
		path = strings.ReplaceAll(path, "{id}", req.GetString("id", ""))

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetUsersSavedAlbumsToolScopes lists the OAuth scopes required by the get-users-saved-albums tool.
var GetUsersSavedAlbumsToolScopes = []string{"user-library-read"}

var GetUsersSavedAlbumsTool = mcp.NewTool("get-users-saved-albums",
	mcp.WithDescription("Get User's Saved Albums\n\n\nGet a list of the albums saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetUsersSavedAlbumsHandler creates a handler for the get-users-saved-albums tool.
func NewGetUsersSavedAlbumsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/albums"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetUsersSavedAudiobooksToolScopes lists the OAuth scopes required by the get-users-saved-audiobooks tool.
var GetUsersSavedAudiobooksToolScopes = []string{"user-library-read"}

var GetUsersSavedAudiobooksTool = mcp.NewTool("get-users-saved-audiobooks",
	mcp.WithDescription("Get User's Saved Audiobooks\n\n\nGet a list of the audiobooks saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetUsersSavedAudiobooksHandler creates a handler for the get-users-saved-audiobooks tool.
func NewGetUsersSavedAudiobooksHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/audiobooks"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetUsersSavedEpisodesToolScopes lists the OAuth scopes required by the get-users-saved-episodes tool.
var GetUsersSavedEpisodesToolScopes = []string{"user-library-read", "user-read-playback-position"}

var GetUsersSavedEpisodesTool = mcp.NewTool("get-users-saved-episodes",
	mcp.WithDescription("Get User's Saved Episodes\n\n\nGet a list of the episodes saved in the current Spotify user's library.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetUsersSavedEpisodesHandler creates a handler for the get-users-saved-episodes tool.
func NewGetUsersSavedEpisodesHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/episodes"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetUsersSavedShowsToolScopes lists the OAuth scopes required by the get-users-saved-shows tool.
var GetUsersSavedShowsToolScopes = []string{"user-library-read"}

var GetUsersSavedShowsTool = mcp.NewTool("get-users-saved-shows",
	mcp.WithDescription("Get User's Saved Shows\n\n\nGet a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetUsersSavedShowsHandler creates a handler for the get-users-saved-shows tool.
func NewGetUsersSavedShowsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/shows"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetUsersSavedTracksToolScopes lists the OAuth scopes required by the get-users-saved-tracks tool.
var GetUsersSavedTracksToolScopes = []string{"user-library-read"}

var GetUsersSavedTracksTool = mcp.NewTool("get-users-saved-tracks",
	mcp.WithDescription("Get User's Saved Tracks\n\n\nGet a list of the songs saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithString(""),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetUsersSavedTracksHandler creates a handler for the get-users-saved-tracks tool.
func NewGetUsersSavedTracksHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/tracks"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// GetUsersTopArtistsAndTracksToolScopes lists the OAuth scopes required by the get-users-top-artists-and-tracks tool.
var GetUsersTopArtistsAndTracksToolScopes = []string{"user-top-read"}

var GetUsersTopArtistsAndTracksTool = mcp.NewTool("get-users-top-artists-and-tracks",
	mcp.WithDescription("Get User's Top Items\n\n\nGet the current user's top artists or tracks based on calculated affinity.\n"),
	mcp.WithString("type", mcp.Required()),
	mcp.WithString("time_range"),
	mcp.WithString(""),
	mcp.WithString(""),
)

// NewGetUsersTopArtistsAndTracksHandler creates a handler for the get-users-top-artists-and-tracks tool.
func NewGetUsersTopArtistsAndTracksHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/top/{type}"
		path = strings.ReplaceAll(path, "{type}", req.GetString("type", ""))

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("time_range", ""); v != "" {
			q.Set("time_range", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// PauseAUsersPlaybackToolScopes lists the OAuth scopes required by the pause-a-users-playback tool.
var PauseAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var PauseAUsersPlaybackTool = mcp.NewTool("pause-a-users-playback",
	mcp.WithDescription("Pause Playback\n\n\nPause playback on the user's account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewPauseAUsersPlaybackHandler creates a handler for the pause-a-users-playback tool.
func NewPauseAUsersPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/pause"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// RemoveItemsPlaylistToolScopes lists the OAuth scopes required by the remove-items-playlist tool.
var RemoveItemsPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var RemoveItemsPlaylistTool = mcp.NewTool("remove-items-playlist",
	mcp.WithDescription("Remove Playlist Items\n\n\nRemove one or more items from a user's playlist.\n"),
	mcp.WithString(""),
)

// NewRemoveItemsPlaylistHandler creates a handler for the remove-items-playlist tool.
func NewRemoveItemsPlaylistHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}/items"

		httpReq, err := http.NewRequestWithContext(ctx, "DELETE", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// RemoveLibraryItemsToolScopes lists the OAuth scopes required by the remove-library-items tool.
var RemoveLibraryItemsToolScopes = []string{"user-library-modify", "user-follow-modify", "playlist-modify-public"}

var RemoveLibraryItemsTool = mcp.NewTool("remove-library-items",
	mcp.WithDescription("Remove Items from Library\n\n\nRemove one or more items from the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewRemoveLibraryItemsHandler creates a handler for the remove-library-items tool.
func NewRemoveLibraryItemsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/library"

		httpReq, err := http.NewRequestWithContext(ctx, "DELETE", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("uris", ""); v != "" {
			q.Set("uris", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// ReorderOrReplacePlaylistsItemsToolScopes lists the OAuth scopes required by the reorder-or-replace-playlists-items tool.
var ReorderOrReplacePlaylistsItemsToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var ReorderOrReplacePlaylistsItemsTool = mcp.NewTool("reorder-or-replace-playlists-items",
	mcp.WithDescription("Update Playlist Items\n\n\nEither reorder or replace items in a playlist depending on the request's parameters.\nTo reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.\nTo replace items, include `uris` as either a query parameter or in the request's body.\nReplacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.\n<br/>\n**Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.\nThese operations can't be applied together in a single request.\n"),
	mcp.WithString(""),
	mcp.WithString("uris"),
)

// NewReorderOrReplacePlaylistsItemsHandler creates a handler for the reorder-or-replace-playlists-items tool.
func NewReorderOrReplacePlaylistsItemsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}/items"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("uris", ""); v != "" {
			q.Set("uris", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SaveLibraryItemsToolScopes lists the OAuth scopes required by the save-library-items tool.
var SaveLibraryItemsToolScopes = []string{"user-library-modify", "user-follow-modify", "playlist-modify-public"}

var SaveLibraryItemsTool = mcp.NewTool("save-library-items",
	mcp.WithDescription("Save Items to Library\n\n\nAdd one or more items to the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewSaveLibraryItemsHandler creates a handler for the save-library-items tool.
func NewSaveLibraryItemsHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/library"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("uris", ""); v != "" {
			q.Set("uris", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SearchToolScopes lists the OAuth scopes required by the search tool.
var SearchToolScopes = []string{}

var SearchTool = mcp.NewTool("search",
	mcp.WithDescription("Search for Item\n\n\nGet Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks\nthat match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("q", mcp.Required()),
	mcp.WithArray("type", mcp.Required()),
	mcp.WithString(""),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
	mcp.WithString("include_external"),
)

// NewSearchHandler creates a handler for the search tool.
func NewSearchHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/search"

		httpReq, err := http.NewRequestWithContext(ctx, "GET", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("q", ""); v != "" {
			q.Set("q", v)
		}
		if v := req.GetString("type", ""); v != "" {
			q.Set("type", v)
		}
		if v := req.GetString("limit", ""); v != "" {
			q.Set("limit", v)
		}
		if v := req.GetString("offset", ""); v != "" {
			q.Set("offset", v)
		}
		if v := req.GetString("include_external", ""); v != "" {
			q.Set("include_external", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SeekToPositionInCurrentlyPlayingTrackToolScopes lists the OAuth scopes required by the seek-to-position-in-currently-playing-track tool.
var SeekToPositionInCurrentlyPlayingTrackToolScopes = []string{"user-modify-playback-state"}

var SeekToPositionInCurrentlyPlayingTrackTool = mcp.NewTool("seek-to-position-in-currently-playing-track",
	mcp.WithDescription("Seek To Position\n\n\nSeeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithNumber("position_ms", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSeekToPositionInCurrentlyPlayingTrackHandler creates a handler for the seek-to-position-in-currently-playing-track tool.
func NewSeekToPositionInCurrentlyPlayingTrackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/seek"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("position_ms", ""); v != "" {
			q.Set("position_ms", v)
		}
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SetRepeatModeOnUsersPlaybackToolScopes lists the OAuth scopes required by the set-repeat-mode-on-users-playback tool.
var SetRepeatModeOnUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var SetRepeatModeOnUsersPlaybackTool = mcp.NewTool("set-repeat-mode-on-users-playback",
	mcp.WithDescription("Set Repeat Mode\n\n\nSet the repeat mode for the user's playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("state", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSetRepeatModeOnUsersPlaybackHandler creates a handler for the set-repeat-mode-on-users-playback tool.
func NewSetRepeatModeOnUsersPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/repeat"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("state", ""); v != "" {
			q.Set("state", v)
		}
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SetVolumeForUsersPlaybackToolScopes lists the OAuth scopes required by the set-volume-for-users-playback tool.
var SetVolumeForUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var SetVolumeForUsersPlaybackTool = mcp.NewTool("set-volume-for-users-playback",
	mcp.WithDescription("Set Playback Volume\n\n\nSet the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithNumber("volume_percent", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSetVolumeForUsersPlaybackHandler creates a handler for the set-volume-for-users-playback tool.
func NewSetVolumeForUsersPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/volume"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("volume_percent", ""); v != "" {
			q.Set("volume_percent", v)
		}
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SkipUsersPlaybackToNextTrackToolScopes lists the OAuth scopes required by the skip-users-playback-to-next-track tool.
var SkipUsersPlaybackToNextTrackToolScopes = []string{"user-modify-playback-state"}

var SkipUsersPlaybackToNextTrackTool = mcp.NewTool("skip-users-playback-to-next-track",
	mcp.WithDescription("Skip To Next\n\n\nSkips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewSkipUsersPlaybackToNextTrackHandler creates a handler for the skip-users-playback-to-next-track tool.
func NewSkipUsersPlaybackToNextTrackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/next"

		httpReq, err := http.NewRequestWithContext(ctx, "POST", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// SkipUsersPlaybackToPreviousTrackToolScopes lists the OAuth scopes required by the skip-users-playback-to-previous-track tool.
var SkipUsersPlaybackToPreviousTrackToolScopes = []string{"user-modify-playback-state"}

var SkipUsersPlaybackToPreviousTrackTool = mcp.NewTool("skip-users-playback-to-previous-track",
	mcp.WithDescription("Skip To Previous\n\n\nSkips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewSkipUsersPlaybackToPreviousTrackHandler creates a handler for the skip-users-playback-to-previous-track tool.
func NewSkipUsersPlaybackToPreviousTrackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/previous"

		httpReq, err := http.NewRequestWithContext(ctx, "POST", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// StartAUsersPlaybackToolScopes lists the OAuth scopes required by the start-a-users-playback tool.
var StartAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var StartAUsersPlaybackTool = mcp.NewTool("start-a-users-playback",
	mcp.WithDescription("Start/Resume Playback\n\n\nStart a new context or resume current playback on the user's active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewStartAUsersPlaybackHandler creates a handler for the start-a-users-playback tool.
func NewStartAUsersPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/play"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// ToggleShuffleForUsersPlaybackToolScopes lists the OAuth scopes required by the toggle-shuffle-for-users-playback tool.
var ToggleShuffleForUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var ToggleShuffleForUsersPlaybackTool = mcp.NewTool("toggle-shuffle-for-users-playback",
	mcp.WithDescription("Toggle Playback Shuffle\n\n\nToggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithBoolean("state", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewToggleShuffleForUsersPlaybackHandler creates a handler for the toggle-shuffle-for-users-playback tool.
func NewToggleShuffleForUsersPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player/shuffle"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		q := httpReq.URL.Query()
		if v := req.GetString("state", ""); v != "" {
			q.Set("state", v)
		}
		if v := req.GetString("device_id", ""); v != "" {
			q.Set("device_id", v)
		}
		httpReq.URL.RawQuery = q.Encode()

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// TransferAUsersPlaybackToolScopes lists the OAuth scopes required by the transfer-a-users-playback tool.
var TransferAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var TransferAUsersPlaybackTool = mcp.NewTool("transfer-a-users-playback",
	mcp.WithDescription("Transfer Playback\n\n\nTransfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
)

// NewTransferAUsersPlaybackHandler creates a handler for the transfer-a-users-playback tool.
func NewTransferAUsersPlaybackHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/me/player"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// UploadCustomPlaylistCoverToolScopes lists the OAuth scopes required by the upload-custom-playlist-cover tool.
var UploadCustomPlaylistCoverToolScopes = []string{"ugc-image-upload", "playlist-modify-public", "playlist-modify-private"}

var UploadCustomPlaylistCoverTool = mcp.NewTool("upload-custom-playlist-cover",
	mcp.WithDescription("Add Custom Playlist Cover Image\n\n\nReplace the image used to represent a specific playlist.\n"),
	mcp.WithString(""),
)

// NewUploadCustomPlaylistCoverHandler creates a handler for the upload-custom-playlist-cover tool.
func NewUploadCustomPlaylistCoverHandler(baseURL string, httpClient *http.Client) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		path := "/playlists/{playlist_id}/images"

		httpReq, err := http.NewRequestWithContext(ctx, "PUT", baseURL+path, nil)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		resp, err := httpClient.Do(httpReq)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}
		defer resp.Body.Close()

		body, err := io.ReadAll(resp.Body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.StatusCode, string(body))), nil
		}

		return mcp.NewToolResultText(string(body)), nil
	}
}

// AllTools contains all generated MCP tool definitions.
var AllTools = []mcp.Tool{
	AddItemsToPlaylistTool,
	AddToQueueTool,
	ChangePlaylistDetailsTool,
	CheckLibraryContainsTool,
	CreatePlaylistTool,
	GetAChapterTool,
	GetAListOfCurrentUsersPlaylistsTool,
	GetAShowTool,
	GetAShowsEpisodesTool,
	GetAUsersAvailableDevicesTool,
	GetAnAlbumTool,
	GetAnAlbumsTracksTool,
	GetAnArtistTool,
	GetAnArtistsAlbumsTool,
	GetAnAudiobookTool,
	GetAnEpisodeTool,
	GetAudiobookChaptersTool,
	GetCurrentUsersProfileTool,
	GetFollowedTool,
	GetInformationAboutTheUsersCurrentPlaybackTool,
	GetPlaylistTool,
	GetPlaylistCoverTool,
	GetPlaylistsItemsTool,
	GetQueueTool,
	GetRecentlyPlayedTool,
	GetTheUsersCurrentlyPlayingTrackTool,
	GetTrackTool,
	GetUsersSavedAlbumsTool,
	GetUsersSavedAudiobooksTool,
	GetUsersSavedEpisodesTool,
	GetUsersSavedShowsTool,
	GetUsersSavedTracksTool,
	GetUsersTopArtistsAndTracksTool,
	PauseAUsersPlaybackTool,
	RemoveItemsPlaylistTool,
	RemoveLibraryItemsTool,
	ReorderOrReplacePlaylistsItemsTool,
	SaveLibraryItemsTool,
	SearchTool,
	SeekToPositionInCurrentlyPlayingTrackTool,
	SetRepeatModeOnUsersPlaybackTool,
	SetVolumeForUsersPlaybackTool,
	SkipUsersPlaybackToNextTrackTool,
	SkipUsersPlaybackToPreviousTrackTool,
	StartAUsersPlaybackTool,
	ToggleShuffleForUsersPlaybackTool,
	TransferAUsersPlaybackTool,
	UploadCustomPlaylistCoverTool,
}

// AllRegistrations returns all generated tool registrations paired with their handler factories.
func AllRegistrations() []ToolRegistration {
	return []ToolRegistration{
		{Tool: AddItemsToPlaylistTool, NewHandler: NewAddItemsToPlaylistHandler},
		{Tool: AddToQueueTool, NewHandler: NewAddToQueueHandler},
		{Tool: ChangePlaylistDetailsTool, NewHandler: NewChangePlaylistDetailsHandler},
		{Tool: CheckLibraryContainsTool, NewHandler: NewCheckLibraryContainsHandler},
		{Tool: CreatePlaylistTool, NewHandler: NewCreatePlaylistHandler},
		{Tool: GetAChapterTool, NewHandler: NewGetAChapterHandler},
		{Tool: GetAListOfCurrentUsersPlaylistsTool, NewHandler: NewGetAListOfCurrentUsersPlaylistsHandler},
		{Tool: GetAShowTool, NewHandler: NewGetAShowHandler},
		{Tool: GetAShowsEpisodesTool, NewHandler: NewGetAShowsEpisodesHandler},
		{Tool: GetAUsersAvailableDevicesTool, NewHandler: NewGetAUsersAvailableDevicesHandler},
		{Tool: GetAnAlbumTool, NewHandler: NewGetAnAlbumHandler},
		{Tool: GetAnAlbumsTracksTool, NewHandler: NewGetAnAlbumsTracksHandler},
		{Tool: GetAnArtistTool, NewHandler: NewGetAnArtistHandler},
		{Tool: GetAnArtistsAlbumsTool, NewHandler: NewGetAnArtistsAlbumsHandler},
		{Tool: GetAnAudiobookTool, NewHandler: NewGetAnAudiobookHandler},
		{Tool: GetAnEpisodeTool, NewHandler: NewGetAnEpisodeHandler},
		{Tool: GetAudiobookChaptersTool, NewHandler: NewGetAudiobookChaptersHandler},
		{Tool: GetCurrentUsersProfileTool, NewHandler: NewGetCurrentUsersProfileHandler},
		{Tool: GetFollowedTool, NewHandler: NewGetFollowedHandler},
		{Tool: GetInformationAboutTheUsersCurrentPlaybackTool, NewHandler: NewGetInformationAboutTheUsersCurrentPlaybackHandler},
		{Tool: GetPlaylistTool, NewHandler: NewGetPlaylistHandler},
		{Tool: GetPlaylistCoverTool, NewHandler: NewGetPlaylistCoverHandler},
		{Tool: GetPlaylistsItemsTool, NewHandler: NewGetPlaylistsItemsHandler},
		{Tool: GetQueueTool, NewHandler: NewGetQueueHandler},
		{Tool: GetRecentlyPlayedTool, NewHandler: NewGetRecentlyPlayedHandler},
		{Tool: GetTheUsersCurrentlyPlayingTrackTool, NewHandler: NewGetTheUsersCurrentlyPlayingTrackHandler},
		{Tool: GetTrackTool, NewHandler: NewGetTrackHandler},
		{Tool: GetUsersSavedAlbumsTool, NewHandler: NewGetUsersSavedAlbumsHandler},
		{Tool: GetUsersSavedAudiobooksTool, NewHandler: NewGetUsersSavedAudiobooksHandler},
		{Tool: GetUsersSavedEpisodesTool, NewHandler: NewGetUsersSavedEpisodesHandler},
		{Tool: GetUsersSavedShowsTool, NewHandler: NewGetUsersSavedShowsHandler},
		{Tool: GetUsersSavedTracksTool, NewHandler: NewGetUsersSavedTracksHandler},
		{Tool: GetUsersTopArtistsAndTracksTool, NewHandler: NewGetUsersTopArtistsAndTracksHandler},
		{Tool: PauseAUsersPlaybackTool, NewHandler: NewPauseAUsersPlaybackHandler},
		{Tool: RemoveItemsPlaylistTool, NewHandler: NewRemoveItemsPlaylistHandler},
		{Tool: RemoveLibraryItemsTool, NewHandler: NewRemoveLibraryItemsHandler},
		{Tool: ReorderOrReplacePlaylistsItemsTool, NewHandler: NewReorderOrReplacePlaylistsItemsHandler},
		{Tool: SaveLibraryItemsTool, NewHandler: NewSaveLibraryItemsHandler},
		{Tool: SearchTool, NewHandler: NewSearchHandler},
		{Tool: SeekToPositionInCurrentlyPlayingTrackTool, NewHandler: NewSeekToPositionInCurrentlyPlayingTrackHandler},
		{Tool: SetRepeatModeOnUsersPlaybackTool, NewHandler: NewSetRepeatModeOnUsersPlaybackHandler},
		{Tool: SetVolumeForUsersPlaybackTool, NewHandler: NewSetVolumeForUsersPlaybackHandler},
		{Tool: SkipUsersPlaybackToNextTrackTool, NewHandler: NewSkipUsersPlaybackToNextTrackHandler},
		{Tool: SkipUsersPlaybackToPreviousTrackTool, NewHandler: NewSkipUsersPlaybackToPreviousTrackHandler},
		{Tool: StartAUsersPlaybackTool, NewHandler: NewStartAUsersPlaybackHandler},
		{Tool: ToggleShuffleForUsersPlaybackTool, NewHandler: NewToggleShuffleForUsersPlaybackHandler},
		{Tool: TransferAUsersPlaybackTool, NewHandler: NewTransferAUsersPlaybackHandler},
		{Tool: UploadCustomPlaylistCoverTool, NewHandler: NewUploadCustomPlaylistCoverHandler},
	}
}
