// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"
	"strings"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// UploadCustomPlaylistCoverToolScopes lists the OAuth scopes required by the upload-custom-playlist-cover tool.
var UploadCustomPlaylistCoverToolScopes = []string{"ugc-image-upload", "playlist-modify-public", "playlist-modify-private"}

var UploadCustomPlaylistCoverTool = mcp.NewTool("upload-custom-playlist-cover",
	mcp.WithDescription("Add Custom Playlist Cover Image\n\n\nReplace the image used to represent a specific playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
)

// NewUploadCustomPlaylistCoverHandler creates a handler for the upload-custom-playlist-cover tool.
func NewUploadCustomPlaylistCoverHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		resp, err := client.UploadCustomPlaylistCoverWithBodyWithResponse(ctx, playlistId, "image/jpeg", strings.NewReader(req.GetString("body", "")))
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
