// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// CheckLibraryContainsToolScopes lists the OAuth scopes required by the check-library-contains tool.
var CheckLibraryContainsToolScopes = []string{"user-library-read", "user-follow-read", "playlist-read-private"}

var CheckLibraryContainsTool = mcp.NewTool("check-library-contains",
	mcp.WithDescription("Check User's Saved Items\n\n\nCheck if one or more items are already saved in the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewCheckLibraryContainsHandler creates a handler for the check-library-contains tool.
func NewCheckLibraryContainsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.CheckLibraryContainsParams{}
		params.Uris = args["uris"].(string)
		resp, err := client.CheckLibraryContainsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
