// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// SeekToPositionInCurrentlyPlayingTrackToolScopes lists the OAuth scopes required by the seek-to-position-in-currently-playing-track tool.
var SeekToPositionInCurrentlyPlayingTrackToolScopes = []string{"user-modify-playback-state"}

var SeekToPositionInCurrentlyPlayingTrackTool = mcp.NewTool("seek-to-position-in-currently-playing-track",
	mcp.WithDescription("Seek To Position\n\n\nSeeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithNumber("position_ms", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSeekToPositionInCurrentlyPlayingTrackHandler creates a handler for the seek-to-position-in-currently-playing-track tool.
func NewSeekToPositionInCurrentlyPlayingTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.SeekToPositionInCurrentlyPlayingTrackParams{}
		params.PositionMs = toInt(args["position_ms"])
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SeekToPositionInCurrentlyPlayingTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
