// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// AddItemsToPlaylistToolScopes lists the OAuth scopes required by the add-items-to-playlist tool.
var AddItemsToPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var AddItemsToPlaylistTool = mcp.NewTool("add-items-to-playlist",
	mcp.WithDescription("Add Items to Playlist\n\n\nAdd one or more items to a user's playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithNumber("position"),
	mcp.WithString("uris"),
)

// NewAddItemsToPlaylistHandler creates a handler for the add-items-to-playlist tool.
func NewAddItemsToPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		params := &spotify.AddItemsToPlaylistParams{}
		if v, ok := args["position"]; ok {
			n := toInt(v)
			params.Position = &n
		}
		if v, ok := args["uris"].(string); ok && v != "" {
			params.Uris = &v
		}
		var body spotify.AddItemsToPlaylistJSONRequestBody
		resp, err := client.AddItemsToPlaylistWithResponse(ctx, playlistId, params, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
