// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAListOfCurrentUsersPlaylistsToolScopes lists the OAuth scopes required by the get-a-list-of-current-users-playlists tool.
var GetAListOfCurrentUsersPlaylistsToolScopes = []string{"playlist-read-private"}

var GetAListOfCurrentUsersPlaylistsTool = mcp.NewTool("get-a-list-of-current-users-playlists",
	mcp.WithDescription("Get Current User's Playlists\n\n\nGet a list of the playlists owned or followed by the current Spotify\nuser.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAListOfCurrentUsersPlaylistsHandler creates a handler for the get-a-list-of-current-users-playlists tool.
func NewGetAListOfCurrentUsersPlaylistsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetAListOfCurrentUsersPlaylistsParams{}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetAListOfCurrentUsersPlaylistsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
