// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAnArtistsAlbumsToolScopes lists the OAuth scopes required by the get-an-artists-albums tool.
var GetAnArtistsAlbumsToolScopes = []string{}

var GetAnArtistsAlbumsTool = mcp.NewTool("get-an-artists-albums",
	mcp.WithDescription("Get Artist's Albums\n\n\nGet Spotify catalog information about an artist's albums.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("include_groups"),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAnArtistsAlbumsHandler creates a handler for the get-an-artists-albums tool.
func NewGetAnArtistsAlbumsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		params := &spotify.GetAnArtistsAlbumsParams{}
		if v, ok := args["include_groups"].(string); ok && v != "" {
			params.IncludeGroups = &v
		}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetAnArtistsAlbumsWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
