// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// ToggleShuffleForUsersPlaybackToolScopes lists the OAuth scopes required by the toggle-shuffle-for-users-playback tool.
var ToggleShuffleForUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var ToggleShuffleForUsersPlaybackTool = mcp.NewTool("toggle-shuffle-for-users-playback",
	mcp.WithDescription("Toggle Playback Shuffle\n\n\nToggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithBoolean("state", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewToggleShuffleForUsersPlaybackHandler creates a handler for the toggle-shuffle-for-users-playback tool.
func NewToggleShuffleForUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.ToggleShuffleForUsersPlaybackParams{}
		params.State = toBool(args["state"])
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		resp, err := client.ToggleShuffleForUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
