// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// StartAUsersPlaybackToolScopes lists the OAuth scopes required by the start-a-users-playback tool.
var StartAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var StartAUsersPlaybackTool = mcp.NewTool("start-a-users-playback",
	mcp.WithDescription("Start/Resume Playback\n\n\nStart a new context or resume current playback on the user's active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewStartAUsersPlaybackHandler creates a handler for the start-a-users-playback tool.
func NewStartAUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.StartAUsersPlaybackParams{}
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		var body spotify.StartAUsersPlaybackJSONRequestBody
		resp, err := client.StartAUsersPlaybackWithResponse(ctx, params, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
