// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAChapterToolScopes lists the OAuth scopes required by the get-a-chapter tool.
var GetAChapterToolScopes = []string{}

var GetAChapterTool = mcp.NewTool("get-a-chapter",
	mcp.WithDescription("Get a Chapter\n\n\nGet Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAChapterHandler creates a handler for the get-a-chapter tool.
func NewGetAChapterHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		params := &spotify.GetAChapterParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		resp, err := client.GetAChapterWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
