// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// SetRepeatModeOnUsersPlaybackToolScopes lists the OAuth scopes required by the set-repeat-mode-on-users-playback tool.
var SetRepeatModeOnUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var SetRepeatModeOnUsersPlaybackTool = mcp.NewTool("set-repeat-mode-on-users-playback",
	mcp.WithDescription("Set Repeat Mode\n\n\nSet the repeat mode for the user's playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("state", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSetRepeatModeOnUsersPlaybackHandler creates a handler for the set-repeat-mode-on-users-playback tool.
func NewSetRepeatModeOnUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.SetRepeatModeOnUsersPlaybackParams{}
		params.State = args["state"].(string)
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SetRepeatModeOnUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
