// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// CreatePlaylistToolScopes lists the OAuth scopes required by the create-playlist tool.
var CreatePlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var CreatePlaylistTool = mcp.NewTool("create-playlist",
	mcp.WithDescription("Create Playlist\n\n\nCreate a playlist for the current Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n"),
)

// NewCreatePlaylistHandler creates a handler for the create-playlist tool.
func NewCreatePlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		var body spotify.CreatePlaylistJSONRequestBody
		resp, err := client.CreatePlaylistWithResponse(ctx, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
