// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"encoding/json"
	"fmt"
	"sort"
	"strings"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// ServerURL is the Spotify API server URL extracted from the OpenAPI spec's servers block.
const ServerURL = "https://api.spotify.com/v1"

// AddItemsToPlaylistToolScopes lists the OAuth scopes required by the add-items-to-playlist tool.
var AddItemsToPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var AddItemsToPlaylistTool = mcp.NewTool("add-items-to-playlist",
	mcp.WithDescription("Add Items to Playlist\n\n\nAdd one or more items to a user's playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithNumber("position"),
	mcp.WithString("uris"),
	mcp.WithArray("uris", mcp.Description("A JSON array of the [Spotify URIs](/documentation/web-api/concepts/spotify-uris-ids) to add. For example: `{\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\", \"spotify:episode:512ojhOuo1ktJprKbVcKyQ\"]}`<br/>A maximum of 100 items can be added in one request. _**Note**: if the `uris` parameter is present in the query string, any URIs listed here in the body will be ignored._\n")),
	mcp.WithNumber("position", mcp.Description("The position to insert the items, a zero-based index. For example, to insert the items in the first position: `position=0` ; to insert the items in the third position: `position=2`. If omitted, the items will be appended to the playlist. Items are added in the order they appear in the uris array. For example: `{\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\",\"spotify:track:1301WleyT98MSxVHPZCA6M\"], \"position\": 3}`\n")),
)

// NewAddItemsToPlaylistHandler creates a handler for the add-items-to-playlist tool.
func NewAddItemsToPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		params := &spotify.AddItemsToPlaylistParams{}
		if v := req.GetInt("position", 0); v != 0 {
			params.Position = &v
		}
		if v := req.GetString("uris", ""); v != "" {
			params.Uris = &v
		}
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		delete(bodyArgs, "playlist_id")
		delete(bodyArgs, "position")
		delete(bodyArgs, "uris")
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.AddItemsToPlaylistJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.AddItemsToPlaylistWithResponse(ctx, playlistId, params, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// AddToQueueToolScopes lists the OAuth scopes required by the add-to-queue tool.
var AddToQueueToolScopes = []string{"user-modify-playback-state"}

var AddToQueueTool = mcp.NewTool("add-to-queue",
	mcp.WithDescription("Add Item to Playback Queue\n\n\nAdd an item to be played next in the user's current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("uri", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewAddToQueueHandler creates a handler for the add-to-queue tool.
func NewAddToQueueHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.AddToQueueParams{}
		params.Uri = req.GetString("uri", "")
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.AddToQueueWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// ChangePlaylistDetailsToolScopes lists the OAuth scopes required by the change-playlist-details tool.
var ChangePlaylistDetailsToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var ChangePlaylistDetailsTool = mcp.NewTool("change-playlist-details",
	mcp.WithDescription("Change Playlist Details\n\n\nChange a playlist's name and public/private state. (The user must, of\ncourse, own the playlist.)\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithBoolean("public", mcp.Description("The playlist's public/private status (if it should be added to the user's profile or not): `true` the playlist will be public, `false` the playlist will be private, `null` the playlist status is not relevant. For more about public/private status, see [Working with Playlists](/documentation/web-api/concepts/playlists)\n")),
	mcp.WithBoolean("collaborative", mcp.Description("If `true`, the playlist will become collaborative and other users will be able to modify the playlist in their Spotify client. <br/>\n_**Note**: You can only set `collaborative` to `true` on non-public playlists._\n")),
	mcp.WithString("description", mcp.Description("Value for playlist description as displayed in Spotify Clients and in the Web API.\n")),
	mcp.WithString("name", mcp.Description("The new name for the playlist, for example `\"My New Playlist Title\"`\n")),
)

// NewChangePlaylistDetailsHandler creates a handler for the change-playlist-details tool.
func NewChangePlaylistDetailsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		delete(bodyArgs, "playlist_id")
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.ChangePlaylistDetailsJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.ChangePlaylistDetailsWithResponse(ctx, playlistId, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// CheckLibraryContainsToolScopes lists the OAuth scopes required by the check-library-contains tool.
var CheckLibraryContainsToolScopes = []string{"user-library-read", "user-follow-read", "playlist-read-private"}

var CheckLibraryContainsTool = mcp.NewTool("check-library-contains",
	mcp.WithDescription("Check User's Saved Items\n\n\nCheck if one or more items are already saved in the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, artists, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewCheckLibraryContainsHandler creates a handler for the check-library-contains tool.
func NewCheckLibraryContainsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.CheckLibraryContainsParams{}
		params.Uris = req.GetString("uris", "")
		resp, err := client.CheckLibraryContainsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// CreatePlaylistToolScopes lists the OAuth scopes required by the create-playlist tool.
var CreatePlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var CreatePlaylistTool = mcp.NewTool("create-playlist",
	mcp.WithDescription("Create Playlist\n\n\nCreate a playlist for the current Spotify user. (The playlist will be empty until\nyou [add tracks](/documentation/web-api/reference/add-tracks-to-playlist).)\nEach user is generally limited to a maximum of 11000 playlists.\n"),
	mcp.WithString("description", mcp.Description("value for playlist description as displayed in Spotify Clients and in the Web API.\n")),
	mcp.WithString("name", mcp.Required(), mcp.Description("The name for the new playlist, for example `\"Your Coolest Playlist\"`. This name does not need to be unique; a user may have several playlists with the same name.\n")),
	mcp.WithBoolean("public", mcp.Description("Defaults to `true`. The playlist's public/private status (if it should be added to the user's profile or not): `true` the playlist will be public, `false` the playlist will be private. To be able to create private playlists, the user must have granted the `playlist-modify-private` [scope](/documentation/web-api/concepts/scopes/#list-of-scopes). For more about public/private status, see [Working with Playlists](/documentation/web-api/concepts/playlists)\n")),
	mcp.WithBoolean("collaborative", mcp.Description("Defaults to `false`. If `true` the playlist will be collaborative. _**Note**: to create a collaborative playlist you must also set `public` to `false`. To create collaborative playlists you must have granted `playlist-modify-private` and `playlist-modify-public` [scopes](/documentation/web-api/concepts/scopes/#list-of-scopes)._\n")),
)

// NewCreatePlaylistHandler creates a handler for the create-playlist tool.
func NewCreatePlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.CreatePlaylistJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.CreatePlaylistWithResponse(ctx, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAChapterToolScopes lists the OAuth scopes required by the get-a-chapter tool.
var GetAChapterToolScopes = []string{}

var GetAChapterTool = mcp.NewTool("get-a-chapter",
	mcp.WithDescription("Get a Chapter\n\n\nGet Spotify catalog information for a single audiobook chapter. Chapters are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAChapterHandler creates a handler for the get-a-chapter tool.
func NewGetAChapterHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAChapterParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetAChapterWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAListOfCurrentUsersPlaylistsToolScopes lists the OAuth scopes required by the get-a-list-of-current-users-playlists tool.
var GetAListOfCurrentUsersPlaylistsToolScopes = []string{"playlist-read-private"}

var GetAListOfCurrentUsersPlaylistsTool = mcp.NewTool("get-a-list-of-current-users-playlists",
	mcp.WithDescription("Get Current User's Playlists\n\n\nGet a list of the playlists owned or followed by the current Spotify\nuser.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAListOfCurrentUsersPlaylistsHandler creates a handler for the get-a-list-of-current-users-playlists tool.
func NewGetAListOfCurrentUsersPlaylistsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetAListOfCurrentUsersPlaylistsParams{}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetAListOfCurrentUsersPlaylistsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAShowToolScopes lists the OAuth scopes required by the get-a-show tool.
var GetAShowToolScopes = []string{"user-read-playback-position"}

var GetAShowTool = mcp.NewTool("get-a-show",
	mcp.WithDescription("Get Show\n\n\nGet Spotify catalog information for a single show identified by its\nunique Spotify ID.\n"),
	mcp.WithString("market"),
	mcp.WithString("id", mcp.Required()),
)

// NewGetAShowHandler creates a handler for the get-a-show tool.
func NewGetAShowHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAShowParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetAShowWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAShowsEpisodesToolScopes lists the OAuth scopes required by the get-a-shows-episodes tool.
var GetAShowsEpisodesToolScopes = []string{"user-read-playback-position"}

var GetAShowsEpisodesTool = mcp.NewTool("get-a-shows-episodes",
	mcp.WithDescription("Get Show Episodes\n\n\nGet Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAShowsEpisodesHandler creates a handler for the get-a-shows-episodes tool.
func NewGetAShowsEpisodesHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAShowsEpisodesParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetAShowsEpisodesWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAUsersAvailableDevicesToolScopes lists the OAuth scopes required by the get-a-users-available-devices tool.
var GetAUsersAvailableDevicesToolScopes = []string{"user-read-playback-state"}

var GetAUsersAvailableDevicesTool = mcp.NewTool("get-a-users-available-devices",
	mcp.WithDescription("Get Available Devices\n\n\nGet information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.\n"),
)

// NewGetAUsersAvailableDevicesHandler creates a handler for the get-a-users-available-devices tool.
func NewGetAUsersAvailableDevicesHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		resp, err := client.GetAUsersAvailableDevicesWithResponse(ctx)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAnAlbumToolScopes lists the OAuth scopes required by the get-an-album tool.
var GetAnAlbumToolScopes = []string{}

var GetAnAlbumTool = mcp.NewTool("get-an-album",
	mcp.WithDescription("Get Album\n\n\nGet Spotify catalog information for a single album.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAnAlbumHandler creates a handler for the get-an-album tool.
func NewGetAnAlbumHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAnAlbumParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetAnAlbumWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAnAlbumsTracksToolScopes lists the OAuth scopes required by the get-an-albums-tracks tool.
var GetAnAlbumsTracksToolScopes = []string{}

var GetAnAlbumsTracksTool = mcp.NewTool("get-an-albums-tracks",
	mcp.WithDescription("Get Album Tracks\n\n\nGet Spotify catalog information about an album’s tracks.\nOptional parameters can be used to limit the number of tracks returned.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAnAlbumsTracksHandler creates a handler for the get-an-albums-tracks tool.
func NewGetAnAlbumsTracksHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAnAlbumsTracksParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetAnAlbumsTracksWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAnArtistToolScopes lists the OAuth scopes required by the get-an-artist tool.
var GetAnArtistToolScopes = []string{}

var GetAnArtistTool = mcp.NewTool("get-an-artist",
	mcp.WithDescription("Get Artist\n\n\nGet Spotify catalog information for a single artist identified by their unique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
)

// NewGetAnArtistHandler creates a handler for the get-an-artist tool.
func NewGetAnArtistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		resp, err := client.GetAnArtistWithResponse(ctx, id)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAnArtistsAlbumsToolScopes lists the OAuth scopes required by the get-an-artists-albums tool.
var GetAnArtistsAlbumsToolScopes = []string{}

var GetAnArtistsAlbumsTool = mcp.NewTool("get-an-artists-albums",
	mcp.WithDescription("Get Artist's Albums\n\n\nGet Spotify catalog information about an artist's albums.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("include_groups"),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAnArtistsAlbumsHandler creates a handler for the get-an-artists-albums tool.
func NewGetAnArtistsAlbumsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAnArtistsAlbumsParams{}
		if v := req.GetString("include_groups", ""); v != "" {
			params.IncludeGroups = &v
		}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetAnArtistsAlbumsWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAnAudiobookToolScopes lists the OAuth scopes required by the get-an-audiobook tool.
var GetAnAudiobookToolScopes = []string{}

var GetAnAudiobookTool = mcp.NewTool("get-an-audiobook",
	mcp.WithDescription("Get an Audiobook\n\n\nGet Spotify catalog information for a single audiobook. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAnAudiobookHandler creates a handler for the get-an-audiobook tool.
func NewGetAnAudiobookHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAnAudiobookParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetAnAudiobookWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAnEpisodeToolScopes lists the OAuth scopes required by the get-an-episode tool.
var GetAnEpisodeToolScopes = []string{"user-read-playback-position"}

var GetAnEpisodeTool = mcp.NewTool("get-an-episode",
	mcp.WithDescription("Get Episode\n\n\nGet Spotify catalog information for a single episode identified by its\nunique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAnEpisodeHandler creates a handler for the get-an-episode tool.
func NewGetAnEpisodeHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAnEpisodeParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetAnEpisodeWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetAudiobookChaptersToolScopes lists the OAuth scopes required by the get-audiobook-chapters tool.
var GetAudiobookChaptersToolScopes = []string{}

var GetAudiobookChaptersTool = mcp.NewTool("get-audiobook-chapters",
	mcp.WithDescription("Get Audiobook Chapters\n\n\nGet Spotify catalog information about an audiobook's chapters. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAudiobookChaptersHandler creates a handler for the get-audiobook-chapters tool.
func NewGetAudiobookChaptersHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetAudiobookChaptersParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetAudiobookChaptersWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetCurrentUsersProfileToolScopes lists the OAuth scopes required by the get-current-users-profile tool.
var GetCurrentUsersProfileToolScopes = []string{"user-read-private", "user-read-email"}

var GetCurrentUsersProfileTool = mcp.NewTool("get-current-users-profile",
	mcp.WithDescription("Get Current User's Profile\n\n\nGet detailed profile information about the current user (including the\ncurrent user's username).\n"),
)

// NewGetCurrentUsersProfileHandler creates a handler for the get-current-users-profile tool.
func NewGetCurrentUsersProfileHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		resp, err := client.GetCurrentUsersProfileWithResponse(ctx)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetFollowedToolScopes lists the OAuth scopes required by the get-followed tool.
var GetFollowedToolScopes = []string{"user-follow-read"}

var GetFollowedTool = mcp.NewTool("get-followed",
	mcp.WithDescription("Get Followed Artists\n\n\nGet the current user's followed artists.\n"),
	mcp.WithString("type", mcp.Required()),
	mcp.WithString("after"),
	mcp.WithNumber("limit"),
)

// NewGetFollowedHandler creates a handler for the get-followed tool.
func NewGetFollowedHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetFollowedParams{}
		params.Type = spotify.GetFollowedParamsType(req.GetString("type", ""))
		if v := req.GetString("after", ""); v != "" {
			params.After = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		resp, err := client.GetFollowedWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetInformationAboutTheUsersCurrentPlaybackToolScopes lists the OAuth scopes required by the get-information-about-the-users-current-playback tool.
var GetInformationAboutTheUsersCurrentPlaybackToolScopes = []string{"user-read-playback-state"}

var GetInformationAboutTheUsersCurrentPlaybackTool = mcp.NewTool("get-information-about-the-users-current-playback",
	mcp.WithDescription("Get Playback State\n\n\nGet information about the user’s current playback state, including track or episode, progress, and active device.\n"),
	mcp.WithString("market"),
	mcp.WithString("additional_types"),
)

// NewGetInformationAboutTheUsersCurrentPlaybackHandler creates a handler for the get-information-about-the-users-current-playback tool.
func NewGetInformationAboutTheUsersCurrentPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetInformationAboutTheUsersCurrentPlaybackParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetString("additional_types", ""); v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetInformationAboutTheUsersCurrentPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetPlaylistToolScopes lists the OAuth scopes required by the get-playlist tool.
var GetPlaylistToolScopes = []string{}

var GetPlaylistTool = mcp.NewTool("get-playlist",
	mcp.WithDescription("Get Playlist\n\n\nGet a playlist owned by a Spotify user.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithString("fields"),
	mcp.WithString("additional_types"),
)

// NewGetPlaylistHandler creates a handler for the get-playlist tool.
func NewGetPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		params := &spotify.GetPlaylistParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetString("fields", ""); v != "" {
			params.Fields = &v
		}
		if v := req.GetString("additional_types", ""); v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetPlaylistWithResponse(ctx, playlistId, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetPlaylistCoverToolScopes lists the OAuth scopes required by the get-playlist-cover tool.
var GetPlaylistCoverToolScopes = []string{}

var GetPlaylistCoverTool = mcp.NewTool("get-playlist-cover",
	mcp.WithDescription("Get Playlist Cover Image\n\n\nGet the current image associated with a specific playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
)

// NewGetPlaylistCoverHandler creates a handler for the get-playlist-cover tool.
func NewGetPlaylistCoverHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		resp, err := client.GetPlaylistCoverWithResponse(ctx, playlistId)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetPlaylistsItemsToolScopes lists the OAuth scopes required by the get-playlists-items tool.
var GetPlaylistsItemsToolScopes = []string{"playlist-read-private"}

var GetPlaylistsItemsTool = mcp.NewTool("get-playlists-items",
	mcp.WithDescription("Get Playlist Items\n\n\nGet full details of the items of a playlist owned by a Spotify user.\n\n**Note**: This endpoint is only accessible for playlists owned by the current user or playlists the user is a collaborator of. A `403 Forbidden` status code will be returned if the user is neither the owner nor a collaborator of the playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithString("fields"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
	mcp.WithString("additional_types"),
)

// NewGetPlaylistsItemsHandler creates a handler for the get-playlists-items tool.
func NewGetPlaylistsItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		params := &spotify.GetPlaylistsItemsParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetString("fields", ""); v != "" {
			params.Fields = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		if v := req.GetString("additional_types", ""); v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetPlaylistsItemsWithResponse(ctx, playlistId, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetQueueToolScopes lists the OAuth scopes required by the get-queue tool.
var GetQueueToolScopes = []string{"user-read-currently-playing", "user-read-playback-state"}

var GetQueueTool = mcp.NewTool("get-queue",
	mcp.WithDescription("Get the User's Queue\n\n\nGet the list of objects that make up the user's queue.\n"),
)

// NewGetQueueHandler creates a handler for the get-queue tool.
func NewGetQueueHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		resp, err := client.GetQueueWithResponse(ctx)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetRecentlyPlayedToolScopes lists the OAuth scopes required by the get-recently-played tool.
var GetRecentlyPlayedToolScopes = []string{"user-read-recently-played"}

var GetRecentlyPlayedTool = mcp.NewTool("get-recently-played",
	mcp.WithDescription("Get Recently Played Tracks\n\n\nGet tracks from the current user's recently played tracks.\n_**Note**: Currently doesn't support podcast episodes._\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("after"),
	mcp.WithNumber("before"),
)

// NewGetRecentlyPlayedHandler creates a handler for the get-recently-played tool.
func NewGetRecentlyPlayedHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetRecentlyPlayedParams{}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("after", 0); v != 0 {
			params.After = &v
		}
		if v := req.GetInt("before", 0); v != 0 {
			params.Before = &v
		}
		resp, err := client.GetRecentlyPlayedWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetTheUsersCurrentlyPlayingTrackToolScopes lists the OAuth scopes required by the get-the-users-currently-playing-track tool.
var GetTheUsersCurrentlyPlayingTrackToolScopes = []string{"user-read-currently-playing"}

var GetTheUsersCurrentlyPlayingTrackTool = mcp.NewTool("get-the-users-currently-playing-track",
	mcp.WithDescription("Get Currently Playing Track\n\n\nGet the object currently being played on the user's Spotify account.\n"),
	mcp.WithString("market"),
	mcp.WithString("additional_types"),
)

// NewGetTheUsersCurrentlyPlayingTrackHandler creates a handler for the get-the-users-currently-playing-track tool.
func NewGetTheUsersCurrentlyPlayingTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetTheUsersCurrentlyPlayingTrackParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetString("additional_types", ""); v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetTheUsersCurrentlyPlayingTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetTrackToolScopes lists the OAuth scopes required by the get-track tool.
var GetTrackToolScopes = []string{}

var GetTrackTool = mcp.NewTool("get-track",
	mcp.WithDescription("Get Track\n\n\nGet Spotify catalog information for a single track identified by its\nunique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetTrackHandler creates a handler for the get-track tool.
func NewGetTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		id := req.GetString("id", "")
		params := &spotify.GetTrackParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetTrackWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetUsersSavedAlbumsToolScopes lists the OAuth scopes required by the get-users-saved-albums tool.
var GetUsersSavedAlbumsToolScopes = []string{"user-library-read"}

var GetUsersSavedAlbumsTool = mcp.NewTool("get-users-saved-albums",
	mcp.WithDescription("Get User's Saved Albums\n\n\nGet a list of the albums saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
	mcp.WithString("market"),
)

// NewGetUsersSavedAlbumsHandler creates a handler for the get-users-saved-albums tool.
func NewGetUsersSavedAlbumsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetUsersSavedAlbumsParams{}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		resp, err := client.GetUsersSavedAlbumsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetUsersSavedAudiobooksToolScopes lists the OAuth scopes required by the get-users-saved-audiobooks tool.
var GetUsersSavedAudiobooksToolScopes = []string{"user-library-read"}

var GetUsersSavedAudiobooksTool = mcp.NewTool("get-users-saved-audiobooks",
	mcp.WithDescription("Get User's Saved Audiobooks\n\n\nGet a list of the audiobooks saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedAudiobooksHandler creates a handler for the get-users-saved-audiobooks tool.
func NewGetUsersSavedAudiobooksHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetUsersSavedAudiobooksParams{}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetUsersSavedAudiobooksWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetUsersSavedEpisodesToolScopes lists the OAuth scopes required by the get-users-saved-episodes tool.
var GetUsersSavedEpisodesToolScopes = []string{"user-library-read", "user-read-playback-position"}

var GetUsersSavedEpisodesTool = mcp.NewTool("get-users-saved-episodes",
	mcp.WithDescription("Get User's Saved Episodes\n\n\nGet a list of the episodes saved in the current Spotify user's library.\n"),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedEpisodesHandler creates a handler for the get-users-saved-episodes tool.
func NewGetUsersSavedEpisodesHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetUsersSavedEpisodesParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetUsersSavedEpisodesWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetUsersSavedShowsToolScopes lists the OAuth scopes required by the get-users-saved-shows tool.
var GetUsersSavedShowsToolScopes = []string{"user-library-read"}

var GetUsersSavedShowsTool = mcp.NewTool("get-users-saved-shows",
	mcp.WithDescription("Get User's Saved Shows\n\n\nGet a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedShowsHandler creates a handler for the get-users-saved-shows tool.
func NewGetUsersSavedShowsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetUsersSavedShowsParams{}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetUsersSavedShowsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetUsersSavedTracksToolScopes lists the OAuth scopes required by the get-users-saved-tracks tool.
var GetUsersSavedTracksToolScopes = []string{"user-library-read"}

var GetUsersSavedTracksTool = mcp.NewTool("get-users-saved-tracks",
	mcp.WithDescription("Get User's Saved Tracks\n\n\nGet a list of the songs saved in the current Spotify user's 'Your Music' library.\n"),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedTracksHandler creates a handler for the get-users-saved-tracks tool.
func NewGetUsersSavedTracksHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.GetUsersSavedTracksParams{}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetUsersSavedTracksWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// GetUsersTopArtistsAndTracksToolScopes lists the OAuth scopes required by the get-users-top-artists-and-tracks tool.
var GetUsersTopArtistsAndTracksToolScopes = []string{"user-top-read"}

var GetUsersTopArtistsAndTracksTool = mcp.NewTool("get-users-top-artists-and-tracks",
	mcp.WithDescription("Get User's Top Items\n\n\nGet the current user's top artists or tracks based on calculated affinity.\n"),
	mcp.WithString("type", mcp.Required()),
	mcp.WithString("time_range"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersTopArtistsAndTracksHandler creates a handler for the get-users-top-artists-and-tracks tool.
func NewGetUsersTopArtistsAndTracksHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		typeParam := spotify.GetUsersTopArtistsAndTracksParamsType(req.GetString("type", ""))
		params := &spotify.GetUsersTopArtistsAndTracksParams{}
		if v := req.GetString("time_range", ""); v != "" {
			params.TimeRange = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		resp, err := client.GetUsersTopArtistsAndTracksWithResponse(ctx, typeParam, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// PauseAUsersPlaybackToolScopes lists the OAuth scopes required by the pause-a-users-playback tool.
var PauseAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var PauseAUsersPlaybackTool = mcp.NewTool("pause-a-users-playback",
	mcp.WithDescription("Pause Playback\n\n\nPause playback on the user's account. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewPauseAUsersPlaybackHandler creates a handler for the pause-a-users-playback tool.
func NewPauseAUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.PauseAUsersPlaybackParams{}
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.PauseAUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// RemoveItemsPlaylistToolScopes lists the OAuth scopes required by the remove-items-playlist tool.
var RemoveItemsPlaylistToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var RemoveItemsPlaylistTool = mcp.NewTool("remove-items-playlist",
	mcp.WithDescription("Remove Playlist Items\n\n\nRemove one or more items from a user's playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithArray("items", mcp.Required(), mcp.Description("An array of objects containing [Spotify URIs](/documentation/web-api/concepts/spotify-uris-ids) of the tracks or episodes to remove.\nFor example: `{ \"items\": [{ \"uri\": \"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\" },{ \"uri\": \"spotify:track:1301WleyT98MSxVHPZCA6M\" }] }`. A maximum of 100 objects can be sent at once.\n")),
	mcp.WithString("snapshot_id", mcp.Description("The playlist's snapshot ID against which you want to make the changes.\nThe API will validate that the specified items exist and in the specified positions and make the changes,\neven if more recent changes have been made to the playlist.\n")),
)

// NewRemoveItemsPlaylistHandler creates a handler for the remove-items-playlist tool.
func NewRemoveItemsPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		delete(bodyArgs, "playlist_id")
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.RemoveItemsPlaylistJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.RemoveItemsPlaylistWithResponse(ctx, playlistId, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// RemoveLibraryItemsToolScopes lists the OAuth scopes required by the remove-library-items tool.
var RemoveLibraryItemsToolScopes = []string{"user-library-modify", "user-follow-modify", "playlist-modify-public"}

var RemoveLibraryItemsTool = mcp.NewTool("remove-library-items",
	mcp.WithDescription("Remove Items from Library\n\n\nRemove one or more items from the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewRemoveLibraryItemsHandler creates a handler for the remove-library-items tool.
func NewRemoveLibraryItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.RemoveLibraryItemsParams{}
		params.Uris = req.GetString("uris", "")
		resp, err := client.RemoveLibraryItemsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// ReorderOrReplacePlaylistsItemsToolScopes lists the OAuth scopes required by the reorder-or-replace-playlists-items tool.
var ReorderOrReplacePlaylistsItemsToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var ReorderOrReplacePlaylistsItemsTool = mcp.NewTool("reorder-or-replace-playlists-items",
	mcp.WithDescription("Update Playlist Items\n\n\nEither reorder or replace items in a playlist depending on the request's parameters.\nTo reorder items, include `range_start`, `insert_before`, `range_length` and `snapshot_id` in the request's body.\nTo replace items, include `uris` as either a query parameter or in the request's body.\nReplacing items in a playlist will overwrite its existing items. This operation can be used for replacing or clearing items in a playlist.\n<br/>\n**Note**: Replace and reorder are mutually exclusive operations which share the same endpoint, but have different parameters.\nThese operations can't be applied together in a single request.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithString("uris"),
	mcp.WithArray("uris"),
	mcp.WithNumber("range_start", mcp.Description("The position of the first item to be reordered.\n")),
	mcp.WithNumber("insert_before", mcp.Description("The position where the items should be inserted.<br/>To reorder the items to the end of the playlist, simply set _insert_before_ to the position after the last item.<br/>Examples:<br/>To reorder the first item to the last position in a playlist with 10 items, set _range_start_ to 0, and _insert_before_ to 10.<br/>To reorder the last item in a playlist with 10 items to the start of the playlist, set _range_start_ to 9, and _insert_before_ to 0.\n")),
	mcp.WithNumber("range_length", mcp.Description("The amount of items to be reordered. Defaults to 1 if not set.<br/>The range of items to be reordered begins from the _range_start_ position, and includes the _range_length_ subsequent items.<br/>Example:<br/>To move the items at index 9-10 to the start of the playlist, _range_start_ is set to 9, and _range_length_ is set to 2.\n")),
	mcp.WithString("snapshot_id", mcp.Description("The playlist's snapshot ID against which you want to make the changes.\n")),
)

// NewReorderOrReplacePlaylistsItemsHandler creates a handler for the reorder-or-replace-playlists-items tool.
func NewReorderOrReplacePlaylistsItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		params := &spotify.ReorderOrReplacePlaylistsItemsParams{}
		if v := req.GetString("uris", ""); v != "" {
			params.Uris = &v
		}
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		delete(bodyArgs, "playlist_id")
		delete(bodyArgs, "uris")
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.ReorderOrReplacePlaylistsItemsJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.ReorderOrReplacePlaylistsItemsWithResponse(ctx, playlistId, params, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SaveLibraryItemsToolScopes lists the OAuth scopes required by the save-library-items tool.
var SaveLibraryItemsToolScopes = []string{"user-library-modify", "user-follow-modify", "playlist-modify-public"}

var SaveLibraryItemsTool = mcp.NewTool("save-library-items",
	mcp.WithDescription("Save Items to Library\n\n\nAdd one or more items to the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewSaveLibraryItemsHandler creates a handler for the save-library-items tool.
func NewSaveLibraryItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SaveLibraryItemsParams{}
		params.Uris = req.GetString("uris", "")
		resp, err := client.SaveLibraryItemsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SearchToolScopes lists the OAuth scopes required by the search tool.
var SearchToolScopes = []string{}

var SearchTool = mcp.NewTool("search",
	mcp.WithDescription("Search for Item\n\n\nGet Spotify catalog information about albums, artists, playlists, tracks, shows, episodes or audiobooks\nthat match a keyword string. Audiobooks are only available within the US, UK, Canada, Ireland, New Zealand and Australia markets.\n"),
	mcp.WithString("q", mcp.Required()),
	mcp.WithArray("type", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
	mcp.WithString("include_external"),
)

// NewSearchHandler creates a handler for the search tool.
func NewSearchHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SearchParams{}
		params.Q = req.GetString("q", "")
		if arr, ok := req.GetArguments()["type"].([]interface{}); ok {
			for _, item := range arr {
				if s, ok := item.(string); ok && s != "" {
					params.Type = append(params.Type, spotify.SearchParamsType(s))
				}
			}
		} else if raw := req.GetString("type", ""); raw != "" {
			for _, s := range strings.Split(raw, ",") {
				if t := strings.TrimSpace(s); t != "" {
					params.Type = append(params.Type, spotify.SearchParamsType(t))
				}
			}
		}
		if v := req.GetString("market", ""); v != "" {
			params.Market = &v
		}
		if v := req.GetInt("limit", 0); v != 0 {
			params.Limit = &v
		}
		if v := req.GetInt("offset", 0); v != 0 {
			params.Offset = &v
		}
		if v := req.GetString("include_external", ""); v != "" {
			ev := spotify.SearchParamsIncludeExternal(v)
			params.IncludeExternal = &ev
		}
		resp, err := client.SearchWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SeekToPositionInCurrentlyPlayingTrackToolScopes lists the OAuth scopes required by the seek-to-position-in-currently-playing-track tool.
var SeekToPositionInCurrentlyPlayingTrackToolScopes = []string{"user-modify-playback-state"}

var SeekToPositionInCurrentlyPlayingTrackTool = mcp.NewTool("seek-to-position-in-currently-playing-track",
	mcp.WithDescription("Seek To Position\n\n\nSeeks to the given position in the user’s currently playing track. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithNumber("position_ms", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSeekToPositionInCurrentlyPlayingTrackHandler creates a handler for the seek-to-position-in-currently-playing-track tool.
func NewSeekToPositionInCurrentlyPlayingTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SeekToPositionInCurrentlyPlayingTrackParams{}
		params.PositionMs = req.GetInt("position_ms", 0)
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SeekToPositionInCurrentlyPlayingTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SetRepeatModeOnUsersPlaybackToolScopes lists the OAuth scopes required by the set-repeat-mode-on-users-playback tool.
var SetRepeatModeOnUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var SetRepeatModeOnUsersPlaybackTool = mcp.NewTool("set-repeat-mode-on-users-playback",
	mcp.WithDescription("Set Repeat Mode\n\n\nSet the repeat mode for the user's playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("state", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSetRepeatModeOnUsersPlaybackHandler creates a handler for the set-repeat-mode-on-users-playback tool.
func NewSetRepeatModeOnUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SetRepeatModeOnUsersPlaybackParams{}
		params.State = req.GetString("state", "")
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SetRepeatModeOnUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SetVolumeForUsersPlaybackToolScopes lists the OAuth scopes required by the set-volume-for-users-playback tool.
var SetVolumeForUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var SetVolumeForUsersPlaybackTool = mcp.NewTool("set-volume-for-users-playback",
	mcp.WithDescription("Set Playback Volume\n\n\nSet the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithNumber("volume_percent", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSetVolumeForUsersPlaybackHandler creates a handler for the set-volume-for-users-playback tool.
func NewSetVolumeForUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SetVolumeForUsersPlaybackParams{}
		params.VolumePercent = req.GetInt("volume_percent", 0)
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SetVolumeForUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SkipUsersPlaybackToNextTrackToolScopes lists the OAuth scopes required by the skip-users-playback-to-next-track tool.
var SkipUsersPlaybackToNextTrackToolScopes = []string{"user-modify-playback-state"}

var SkipUsersPlaybackToNextTrackTool = mcp.NewTool("skip-users-playback-to-next-track",
	mcp.WithDescription("Skip To Next\n\n\nSkips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewSkipUsersPlaybackToNextTrackHandler creates a handler for the skip-users-playback-to-next-track tool.
func NewSkipUsersPlaybackToNextTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SkipUsersPlaybackToNextTrackParams{}
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SkipUsersPlaybackToNextTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// SkipUsersPlaybackToPreviousTrackToolScopes lists the OAuth scopes required by the skip-users-playback-to-previous-track tool.
var SkipUsersPlaybackToPreviousTrackToolScopes = []string{"user-modify-playback-state"}

var SkipUsersPlaybackToPreviousTrackTool = mcp.NewTool("skip-users-playback-to-previous-track",
	mcp.WithDescription("Skip To Previous\n\n\nSkips to previous track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewSkipUsersPlaybackToPreviousTrackHandler creates a handler for the skip-users-playback-to-previous-track tool.
func NewSkipUsersPlaybackToPreviousTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.SkipUsersPlaybackToPreviousTrackParams{}
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SkipUsersPlaybackToPreviousTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// StartAUsersPlaybackToolScopes lists the OAuth scopes required by the start-a-users-playback tool.
var StartAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var StartAUsersPlaybackTool = mcp.NewTool("start-a-users-playback",
	mcp.WithDescription("Start/Resume Playback\n\n\nStart a new context or resume current playback on the user's active device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
	mcp.WithString("context_uri", mcp.Description("Optional. Spotify URI of the context to play.\nValid contexts are albums, artists & playlists.\n`{context_uri:\"spotify:album:1Je1IMUlBXcx1Fz0WE7oPT\"}`\n")),
	mcp.WithArray("uris", mcp.Description("Optional. A JSON array of the Spotify track URIs to play.\nFor example: `{\"uris\": [\"spotify:track:4iV5W9uYEdYUVa79Axb7Rh\", \"spotify:track:1301WleyT98MSxVHPZCA6M\"]}`\n")),
	mcp.WithString("offset", mcp.Description("Optional. Indicates from where in the context playback should start. Only available when context_uri corresponds to an album or playlist object\n\"position\" is zero based and can’t be negative. Example: `\"offset\": {\"position\": 5}`\n\"uri\" is a string representing the uri of the item to start at. Example: `\"offset\": {\"uri\": \"spotify:track:1301WleyT98MSxVHPZCA6M\"}`\n")),
	mcp.WithNumber("position_ms", mcp.Description("integer")),
)

// NewStartAUsersPlaybackHandler creates a handler for the start-a-users-playback tool.
func NewStartAUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.StartAUsersPlaybackParams{}
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		delete(bodyArgs, "device_id")
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.StartAUsersPlaybackJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.StartAUsersPlaybackWithResponse(ctx, params, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// ToggleShuffleForUsersPlaybackToolScopes lists the OAuth scopes required by the toggle-shuffle-for-users-playback tool.
var ToggleShuffleForUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var ToggleShuffleForUsersPlaybackTool = mcp.NewTool("toggle-shuffle-for-users-playback",
	mcp.WithDescription("Toggle Playback Shuffle\n\n\nToggle shuffle on or off for user’s playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithBoolean("state", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewToggleShuffleForUsersPlaybackHandler creates a handler for the toggle-shuffle-for-users-playback tool.
func NewToggleShuffleForUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		params := &spotify.ToggleShuffleForUsersPlaybackParams{}
		params.State = req.GetString("state", "") == "true"
		if v := req.GetString("device_id", ""); v != "" {
			params.DeviceId = &v
		}
		resp, err := client.ToggleShuffleForUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// TransferAUsersPlaybackToolScopes lists the OAuth scopes required by the transfer-a-users-playback tool.
var TransferAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var TransferAUsersPlaybackTool = mcp.NewTool("transfer-a-users-playback",
	mcp.WithDescription("Transfer Playback\n\n\nTransfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithArray("device_ids", mcp.Required(), mcp.Description("A JSON array containing the ID of the device on which playback should be started/transferred.<br/>For example:`{device_ids:[\"74ASZWbe4lXaubB36ztrGX\"]}`<br/>_**Note**: Although an array is accepted, only a single device_id is currently supported. Supplying more than one will return `400 Bad Request`_\n")),
	mcp.WithBoolean("play", mcp.Description("**true**: ensure playback happens on new device.<br/>**false** or not provided: keep the current playback state.\n")),
)

// NewTransferAUsersPlaybackHandler creates a handler for the transfer-a-users-playback tool.
func NewTransferAUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		bodyArgs := make(map[string]interface{})
		for k, v := range req.GetArguments() {
			bodyArgs[k] = v
		}
		bodyJSON, err := json.Marshal(bodyArgs)
		if err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("marshaling request body: %v", err)), nil
		}
		var body spotify.TransferAUsersPlaybackJSONRequestBody
		if err := json.Unmarshal(bodyJSON, &body); err != nil {
			return mcp.NewToolResultError(fmt.Sprintf("unmarshaling request body: %v", err)), nil
		}
		resp, err := client.TransferAUsersPlaybackWithResponse(ctx, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// UploadCustomPlaylistCoverToolScopes lists the OAuth scopes required by the upload-custom-playlist-cover tool.
var UploadCustomPlaylistCoverToolScopes = []string{"ugc-image-upload", "playlist-modify-public", "playlist-modify-private"}

var UploadCustomPlaylistCoverTool = mcp.NewTool("upload-custom-playlist-cover",
	mcp.WithDescription("Add Custom Playlist Cover Image\n\n\nReplace the image used to represent a specific playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
)

// NewUploadCustomPlaylistCoverHandler creates a handler for the upload-custom-playlist-cover tool.
func NewUploadCustomPlaylistCoverHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		playlistId := req.GetString("playlist_id", "")
		resp, err := client.UploadCustomPlaylistCoverWithBodyWithResponse(ctx, playlistId, "image/jpeg", strings.NewReader(req.GetString("body", "")))
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}

// AllTools contains all generated MCP tool definitions.
var AllTools = []mcp.Tool{
	AddItemsToPlaylistTool,
	AddToQueueTool,
	ChangePlaylistDetailsTool,
	CheckLibraryContainsTool,
	CreatePlaylistTool,
	GetAChapterTool,
	GetAListOfCurrentUsersPlaylistsTool,
	GetAShowTool,
	GetAShowsEpisodesTool,
	GetAUsersAvailableDevicesTool,
	GetAnAlbumTool,
	GetAnAlbumsTracksTool,
	GetAnArtistTool,
	GetAnArtistsAlbumsTool,
	GetAnAudiobookTool,
	GetAnEpisodeTool,
	GetAudiobookChaptersTool,
	GetCurrentUsersProfileTool,
	GetFollowedTool,
	GetInformationAboutTheUsersCurrentPlaybackTool,
	GetPlaylistTool,
	GetPlaylistCoverTool,
	GetPlaylistsItemsTool,
	GetQueueTool,
	GetRecentlyPlayedTool,
	GetTheUsersCurrentlyPlayingTrackTool,
	GetTrackTool,
	GetUsersSavedAlbumsTool,
	GetUsersSavedAudiobooksTool,
	GetUsersSavedEpisodesTool,
	GetUsersSavedShowsTool,
	GetUsersSavedTracksTool,
	GetUsersTopArtistsAndTracksTool,
	PauseAUsersPlaybackTool,
	RemoveItemsPlaylistTool,
	RemoveLibraryItemsTool,
	ReorderOrReplacePlaylistsItemsTool,
	SaveLibraryItemsTool,
	SearchTool,
	SeekToPositionInCurrentlyPlayingTrackTool,
	SetRepeatModeOnUsersPlaybackTool,
	SetVolumeForUsersPlaybackTool,
	SkipUsersPlaybackToNextTrackTool,
	SkipUsersPlaybackToPreviousTrackTool,
	StartAUsersPlaybackTool,
	ToggleShuffleForUsersPlaybackTool,
	TransferAUsersPlaybackTool,
	UploadCustomPlaylistCoverTool,
}

// AllRegistrations returns all generated tool registrations paired with their handler factories.
func AllRegistrations() []ToolRegistration {
	return []ToolRegistration{
		{Tool: AddItemsToPlaylistTool, NewHandler: NewAddItemsToPlaylistHandler},
		{Tool: AddToQueueTool, NewHandler: NewAddToQueueHandler},
		{Tool: ChangePlaylistDetailsTool, NewHandler: NewChangePlaylistDetailsHandler},
		{Tool: CheckLibraryContainsTool, NewHandler: NewCheckLibraryContainsHandler},
		{Tool: CreatePlaylistTool, NewHandler: NewCreatePlaylistHandler},
		{Tool: GetAChapterTool, NewHandler: NewGetAChapterHandler},
		{Tool: GetAListOfCurrentUsersPlaylistsTool, NewHandler: NewGetAListOfCurrentUsersPlaylistsHandler},
		{Tool: GetAShowTool, NewHandler: NewGetAShowHandler},
		{Tool: GetAShowsEpisodesTool, NewHandler: NewGetAShowsEpisodesHandler},
		{Tool: GetAUsersAvailableDevicesTool, NewHandler: NewGetAUsersAvailableDevicesHandler},
		{Tool: GetAnAlbumTool, NewHandler: NewGetAnAlbumHandler},
		{Tool: GetAnAlbumsTracksTool, NewHandler: NewGetAnAlbumsTracksHandler},
		{Tool: GetAnArtistTool, NewHandler: NewGetAnArtistHandler},
		{Tool: GetAnArtistsAlbumsTool, NewHandler: NewGetAnArtistsAlbumsHandler},
		{Tool: GetAnAudiobookTool, NewHandler: NewGetAnAudiobookHandler},
		{Tool: GetAnEpisodeTool, NewHandler: NewGetAnEpisodeHandler},
		{Tool: GetAudiobookChaptersTool, NewHandler: NewGetAudiobookChaptersHandler},
		{Tool: GetCurrentUsersProfileTool, NewHandler: NewGetCurrentUsersProfileHandler},
		{Tool: GetFollowedTool, NewHandler: NewGetFollowedHandler},
		{Tool: GetInformationAboutTheUsersCurrentPlaybackTool, NewHandler: NewGetInformationAboutTheUsersCurrentPlaybackHandler},
		{Tool: GetPlaylistTool, NewHandler: NewGetPlaylistHandler},
		{Tool: GetPlaylistCoverTool, NewHandler: NewGetPlaylistCoverHandler},
		{Tool: GetPlaylistsItemsTool, NewHandler: NewGetPlaylistsItemsHandler},
		{Tool: GetQueueTool, NewHandler: NewGetQueueHandler},
		{Tool: GetRecentlyPlayedTool, NewHandler: NewGetRecentlyPlayedHandler},
		{Tool: GetTheUsersCurrentlyPlayingTrackTool, NewHandler: NewGetTheUsersCurrentlyPlayingTrackHandler},
		{Tool: GetTrackTool, NewHandler: NewGetTrackHandler},
		{Tool: GetUsersSavedAlbumsTool, NewHandler: NewGetUsersSavedAlbumsHandler},
		{Tool: GetUsersSavedAudiobooksTool, NewHandler: NewGetUsersSavedAudiobooksHandler},
		{Tool: GetUsersSavedEpisodesTool, NewHandler: NewGetUsersSavedEpisodesHandler},
		{Tool: GetUsersSavedShowsTool, NewHandler: NewGetUsersSavedShowsHandler},
		{Tool: GetUsersSavedTracksTool, NewHandler: NewGetUsersSavedTracksHandler},
		{Tool: GetUsersTopArtistsAndTracksTool, NewHandler: NewGetUsersTopArtistsAndTracksHandler},
		{Tool: PauseAUsersPlaybackTool, NewHandler: NewPauseAUsersPlaybackHandler},
		{Tool: RemoveItemsPlaylistTool, NewHandler: NewRemoveItemsPlaylistHandler},
		{Tool: RemoveLibraryItemsTool, NewHandler: NewRemoveLibraryItemsHandler},
		{Tool: ReorderOrReplacePlaylistsItemsTool, NewHandler: NewReorderOrReplacePlaylistsItemsHandler},
		{Tool: SaveLibraryItemsTool, NewHandler: NewSaveLibraryItemsHandler},
		{Tool: SearchTool, NewHandler: NewSearchHandler},
		{Tool: SeekToPositionInCurrentlyPlayingTrackTool, NewHandler: NewSeekToPositionInCurrentlyPlayingTrackHandler},
		{Tool: SetRepeatModeOnUsersPlaybackTool, NewHandler: NewSetRepeatModeOnUsersPlaybackHandler},
		{Tool: SetVolumeForUsersPlaybackTool, NewHandler: NewSetVolumeForUsersPlaybackHandler},
		{Tool: SkipUsersPlaybackToNextTrackTool, NewHandler: NewSkipUsersPlaybackToNextTrackHandler},
		{Tool: SkipUsersPlaybackToPreviousTrackTool, NewHandler: NewSkipUsersPlaybackToPreviousTrackHandler},
		{Tool: StartAUsersPlaybackTool, NewHandler: NewStartAUsersPlaybackHandler},
		{Tool: ToggleShuffleForUsersPlaybackTool, NewHandler: NewToggleShuffleForUsersPlaybackHandler},
		{Tool: TransferAUsersPlaybackTool, NewHandler: NewTransferAUsersPlaybackHandler},
		{Tool: UploadCustomPlaylistCoverTool, NewHandler: NewUploadCustomPlaylistCoverHandler},
	}
}

// AllScopes returns the deduplicated, sorted union of all OAuth scopes required by all tools.
func AllScopes() []string {
	seen := make(map[string]bool)
	for _, s := range AddItemsToPlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range AddToQueueToolScopes {
		seen[s] = true
	}
	for _, s := range ChangePlaylistDetailsToolScopes {
		seen[s] = true
	}
	for _, s := range CheckLibraryContainsToolScopes {
		seen[s] = true
	}
	for _, s := range CreatePlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range GetAChapterToolScopes {
		seen[s] = true
	}
	for _, s := range GetAListOfCurrentUsersPlaylistsToolScopes {
		seen[s] = true
	}
	for _, s := range GetAShowToolScopes {
		seen[s] = true
	}
	for _, s := range GetAShowsEpisodesToolScopes {
		seen[s] = true
	}
	for _, s := range GetAUsersAvailableDevicesToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnAlbumToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnAlbumsTracksToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnArtistToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnArtistsAlbumsToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnAudiobookToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnEpisodeToolScopes {
		seen[s] = true
	}
	for _, s := range GetAudiobookChaptersToolScopes {
		seen[s] = true
	}
	for _, s := range GetCurrentUsersProfileToolScopes {
		seen[s] = true
	}
	for _, s := range GetFollowedToolScopes {
		seen[s] = true
	}
	for _, s := range GetInformationAboutTheUsersCurrentPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range GetPlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range GetPlaylistCoverToolScopes {
		seen[s] = true
	}
	for _, s := range GetPlaylistsItemsToolScopes {
		seen[s] = true
	}
	for _, s := range GetQueueToolScopes {
		seen[s] = true
	}
	for _, s := range GetRecentlyPlayedToolScopes {
		seen[s] = true
	}
	for _, s := range GetTheUsersCurrentlyPlayingTrackToolScopes {
		seen[s] = true
	}
	for _, s := range GetTrackToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedAlbumsToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedAudiobooksToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedEpisodesToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedShowsToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedTracksToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersTopArtistsAndTracksToolScopes {
		seen[s] = true
	}
	for _, s := range PauseAUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range RemoveItemsPlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range RemoveLibraryItemsToolScopes {
		seen[s] = true
	}
	for _, s := range ReorderOrReplacePlaylistsItemsToolScopes {
		seen[s] = true
	}
	for _, s := range SaveLibraryItemsToolScopes {
		seen[s] = true
	}
	for _, s := range SearchToolScopes {
		seen[s] = true
	}
	for _, s := range SeekToPositionInCurrentlyPlayingTrackToolScopes {
		seen[s] = true
	}
	for _, s := range SetRepeatModeOnUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range SetVolumeForUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range SkipUsersPlaybackToNextTrackToolScopes {
		seen[s] = true
	}
	for _, s := range SkipUsersPlaybackToPreviousTrackToolScopes {
		seen[s] = true
	}
	for _, s := range StartAUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range ToggleShuffleForUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range TransferAUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range UploadCustomPlaylistCoverToolScopes {
		seen[s] = true
	}
	result := make([]string, 0, len(seen))
	for s := range seen {
		result = append(result, s)
	}
	sort.Strings(result)
	return result
}
