// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetInformationAboutTheUsersCurrentPlaybackToolScopes lists the OAuth scopes required by the get-information-about-the-users-current-playback tool.
var GetInformationAboutTheUsersCurrentPlaybackToolScopes = []string{"user-read-playback-state"}

var GetInformationAboutTheUsersCurrentPlaybackTool = mcp.NewTool("get-information-about-the-users-current-playback",
	mcp.WithDescription("Get Playback State\n\n\nGet information about the user’s current playback state, including track or episode, progress, and active device.\n"),
	mcp.WithString("market"),
	mcp.WithString("additional_types"),
)

// NewGetInformationAboutTheUsersCurrentPlaybackHandler creates a handler for the get-information-about-the-users-current-playback tool.
func NewGetInformationAboutTheUsersCurrentPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetInformationAboutTheUsersCurrentPlaybackParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["additional_types"].(string); ok && v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetInformationAboutTheUsersCurrentPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
