// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetUsersSavedShowsToolScopes lists the OAuth scopes required by the get-users-saved-shows tool.
var GetUsersSavedShowsToolScopes = []string{"user-library-read"}

var GetUsersSavedShowsTool = mcp.NewTool("get-users-saved-shows",
	mcp.WithDescription("Get User's Saved Shows\n\n\nGet a list of shows saved in the current Spotify user's library. Optional parameters can be used to limit the number of shows returned.\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedShowsHandler creates a handler for the get-users-saved-shows tool.
func NewGetUsersSavedShowsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetUsersSavedShowsParams{}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetUsersSavedShowsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
