// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetUsersSavedEpisodesToolScopes lists the OAuth scopes required by the get-users-saved-episodes tool.
var GetUsersSavedEpisodesToolScopes = []string{"user-library-read", "user-read-playback-position"}

var GetUsersSavedEpisodesTool = mcp.NewTool("get-users-saved-episodes",
	mcp.WithDescription("Get User's Saved Episodes\n\n\nGet a list of the episodes saved in the current Spotify user's library.\n"),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetUsersSavedEpisodesHandler creates a handler for the get-users-saved-episodes tool.
func NewGetUsersSavedEpisodesHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetUsersSavedEpisodesParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetUsersSavedEpisodesWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
