// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// SetVolumeForUsersPlaybackToolScopes lists the OAuth scopes required by the set-volume-for-users-playback tool.
var SetVolumeForUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var SetVolumeForUsersPlaybackTool = mcp.NewTool("set-volume-for-users-playback",
	mcp.WithDescription("Set Playback Volume\n\n\nSet the volume for the user’s current playback device. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithNumber("volume_percent", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewSetVolumeForUsersPlaybackHandler creates a handler for the set-volume-for-users-playback tool.
func NewSetVolumeForUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.SetVolumeForUsersPlaybackParams{}
		params.VolumePercent = toInt(args["volume_percent"])
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SetVolumeForUsersPlaybackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
