// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// SaveLibraryItemsToolScopes lists the OAuth scopes required by the save-library-items tool.
var SaveLibraryItemsToolScopes = []string{"user-library-modify", "user-follow-modify", "playlist-modify-public"}

var SaveLibraryItemsTool = mcp.NewTool("save-library-items",
	mcp.WithDescription("Save Items to Library\n\n\nAdd one or more items to the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewSaveLibraryItemsHandler creates a handler for the save-library-items tool.
func NewSaveLibraryItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.SaveLibraryItemsParams{}
		params.Uris = args["uris"].(string)
		resp, err := client.SaveLibraryItemsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
