// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetPlaylistCoverToolScopes lists the OAuth scopes required by the get-playlist-cover tool.
var GetPlaylistCoverToolScopes = []string{}

var GetPlaylistCoverTool = mcp.NewTool("get-playlist-cover",
	mcp.WithDescription("Get Playlist Cover Image\n\n\nGet the current image associated with a specific playlist.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
)

// NewGetPlaylistCoverHandler creates a handler for the get-playlist-cover tool.
func NewGetPlaylistCoverHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		resp, err := client.GetPlaylistCoverWithResponse(ctx, playlistId)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
