// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// ChangePlaylistDetailsToolScopes lists the OAuth scopes required by the change-playlist-details tool.
var ChangePlaylistDetailsToolScopes = []string{"playlist-modify-public", "playlist-modify-private"}

var ChangePlaylistDetailsTool = mcp.NewTool("change-playlist-details",
	mcp.WithDescription("Change Playlist Details\n\n\nChange a playlist's name and public/private state. (The user must, of\ncourse, own the playlist.)\n"),
	mcp.WithString("playlist_id", mcp.Required()),
)

// NewChangePlaylistDetailsHandler creates a handler for the change-playlist-details tool.
func NewChangePlaylistDetailsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		var body spotify.ChangePlaylistDetailsJSONRequestBody
		resp, err := client.ChangePlaylistDetailsWithResponse(ctx, playlistId, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
