// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"sort"

	"github.com/mark3labs/mcp-go/mcp"
)

// ServerURL is the Spotify API server URL extracted from the OpenAPI spec's servers block.
const ServerURL = "https://api.spotify.com/v1"

// AllTools contains all generated MCP tool definitions.
var AllTools = []mcp.Tool{
	AddItemsToPlaylistTool,
	AddToQueueTool,
	ChangePlaylistDetailsTool,
	CheckLibraryContainsTool,
	CreatePlaylistTool,
	GetAChapterTool,
	GetAListOfCurrentUsersPlaylistsTool,
	GetAShowTool,
	GetAShowsEpisodesTool,
	GetAUsersAvailableDevicesTool,
	GetAnAlbumTool,
	GetAnAlbumsTracksTool,
	GetAnArtistTool,
	GetAnArtistsAlbumsTool,
	GetAnAudiobookTool,
	GetAnEpisodeTool,
	GetAudiobookChaptersTool,
	GetCurrentUsersProfileTool,
	GetFollowedTool,
	GetInformationAboutTheUsersCurrentPlaybackTool,
	GetPlaylistTool,
	GetPlaylistCoverTool,
	GetPlaylistsItemsTool,
	GetQueueTool,
	GetRecentlyPlayedTool,
	GetTheUsersCurrentlyPlayingTrackTool,
	GetTrackTool,
	GetUsersSavedAlbumsTool,
	GetUsersSavedAudiobooksTool,
	GetUsersSavedEpisodesTool,
	GetUsersSavedShowsTool,
	GetUsersSavedTracksTool,
	GetUsersTopArtistsAndTracksTool,
	PauseAUsersPlaybackTool,
	RemoveItemsPlaylistTool,
	RemoveLibraryItemsTool,
	ReorderOrReplacePlaylistsItemsTool,
	SaveLibraryItemsTool,
	SearchTool,
	SeekToPositionInCurrentlyPlayingTrackTool,
	SetRepeatModeOnUsersPlaybackTool,
	SetVolumeForUsersPlaybackTool,
	SkipUsersPlaybackToNextTrackTool,
	SkipUsersPlaybackToPreviousTrackTool,
	StartAUsersPlaybackTool,
	ToggleShuffleForUsersPlaybackTool,
	TransferAUsersPlaybackTool,
	UploadCustomPlaylistCoverTool,
}

// AllRegistrations returns all generated tool registrations paired with their handler factories.
func AllRegistrations() []ToolRegistration {
	return []ToolRegistration{
		{Tool: AddItemsToPlaylistTool, NewHandler: NewAddItemsToPlaylistHandler},
		{Tool: AddToQueueTool, NewHandler: NewAddToQueueHandler},
		{Tool: ChangePlaylistDetailsTool, NewHandler: NewChangePlaylistDetailsHandler},
		{Tool: CheckLibraryContainsTool, NewHandler: NewCheckLibraryContainsHandler},
		{Tool: CreatePlaylistTool, NewHandler: NewCreatePlaylistHandler},
		{Tool: GetAChapterTool, NewHandler: NewGetAChapterHandler},
		{Tool: GetAListOfCurrentUsersPlaylistsTool, NewHandler: NewGetAListOfCurrentUsersPlaylistsHandler},
		{Tool: GetAShowTool, NewHandler: NewGetAShowHandler},
		{Tool: GetAShowsEpisodesTool, NewHandler: NewGetAShowsEpisodesHandler},
		{Tool: GetAUsersAvailableDevicesTool, NewHandler: NewGetAUsersAvailableDevicesHandler},
		{Tool: GetAnAlbumTool, NewHandler: NewGetAnAlbumHandler},
		{Tool: GetAnAlbumsTracksTool, NewHandler: NewGetAnAlbumsTracksHandler},
		{Tool: GetAnArtistTool, NewHandler: NewGetAnArtistHandler},
		{Tool: GetAnArtistsAlbumsTool, NewHandler: NewGetAnArtistsAlbumsHandler},
		{Tool: GetAnAudiobookTool, NewHandler: NewGetAnAudiobookHandler},
		{Tool: GetAnEpisodeTool, NewHandler: NewGetAnEpisodeHandler},
		{Tool: GetAudiobookChaptersTool, NewHandler: NewGetAudiobookChaptersHandler},
		{Tool: GetCurrentUsersProfileTool, NewHandler: NewGetCurrentUsersProfileHandler},
		{Tool: GetFollowedTool, NewHandler: NewGetFollowedHandler},
		{Tool: GetInformationAboutTheUsersCurrentPlaybackTool, NewHandler: NewGetInformationAboutTheUsersCurrentPlaybackHandler},
		{Tool: GetPlaylistTool, NewHandler: NewGetPlaylistHandler},
		{Tool: GetPlaylistCoverTool, NewHandler: NewGetPlaylistCoverHandler},
		{Tool: GetPlaylistsItemsTool, NewHandler: NewGetPlaylistsItemsHandler},
		{Tool: GetQueueTool, NewHandler: NewGetQueueHandler},
		{Tool: GetRecentlyPlayedTool, NewHandler: NewGetRecentlyPlayedHandler},
		{Tool: GetTheUsersCurrentlyPlayingTrackTool, NewHandler: NewGetTheUsersCurrentlyPlayingTrackHandler},
		{Tool: GetTrackTool, NewHandler: NewGetTrackHandler},
		{Tool: GetUsersSavedAlbumsTool, NewHandler: NewGetUsersSavedAlbumsHandler},
		{Tool: GetUsersSavedAudiobooksTool, NewHandler: NewGetUsersSavedAudiobooksHandler},
		{Tool: GetUsersSavedEpisodesTool, NewHandler: NewGetUsersSavedEpisodesHandler},
		{Tool: GetUsersSavedShowsTool, NewHandler: NewGetUsersSavedShowsHandler},
		{Tool: GetUsersSavedTracksTool, NewHandler: NewGetUsersSavedTracksHandler},
		{Tool: GetUsersTopArtistsAndTracksTool, NewHandler: NewGetUsersTopArtistsAndTracksHandler},
		{Tool: PauseAUsersPlaybackTool, NewHandler: NewPauseAUsersPlaybackHandler},
		{Tool: RemoveItemsPlaylistTool, NewHandler: NewRemoveItemsPlaylistHandler},
		{Tool: RemoveLibraryItemsTool, NewHandler: NewRemoveLibraryItemsHandler},
		{Tool: ReorderOrReplacePlaylistsItemsTool, NewHandler: NewReorderOrReplacePlaylistsItemsHandler},
		{Tool: SaveLibraryItemsTool, NewHandler: NewSaveLibraryItemsHandler},
		{Tool: SearchTool, NewHandler: NewSearchHandler},
		{Tool: SeekToPositionInCurrentlyPlayingTrackTool, NewHandler: NewSeekToPositionInCurrentlyPlayingTrackHandler},
		{Tool: SetRepeatModeOnUsersPlaybackTool, NewHandler: NewSetRepeatModeOnUsersPlaybackHandler},
		{Tool: SetVolumeForUsersPlaybackTool, NewHandler: NewSetVolumeForUsersPlaybackHandler},
		{Tool: SkipUsersPlaybackToNextTrackTool, NewHandler: NewSkipUsersPlaybackToNextTrackHandler},
		{Tool: SkipUsersPlaybackToPreviousTrackTool, NewHandler: NewSkipUsersPlaybackToPreviousTrackHandler},
		{Tool: StartAUsersPlaybackTool, NewHandler: NewStartAUsersPlaybackHandler},
		{Tool: ToggleShuffleForUsersPlaybackTool, NewHandler: NewToggleShuffleForUsersPlaybackHandler},
		{Tool: TransferAUsersPlaybackTool, NewHandler: NewTransferAUsersPlaybackHandler},
		{Tool: UploadCustomPlaylistCoverTool, NewHandler: NewUploadCustomPlaylistCoverHandler},
	}
}

// AllScopes returns the deduplicated, sorted union of all OAuth scopes required by all tools.
func AllScopes() []string {
	seen := make(map[string]bool)
	for _, s := range AddItemsToPlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range AddToQueueToolScopes {
		seen[s] = true
	}
	for _, s := range ChangePlaylistDetailsToolScopes {
		seen[s] = true
	}
	for _, s := range CheckLibraryContainsToolScopes {
		seen[s] = true
	}
	for _, s := range CreatePlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range GetAChapterToolScopes {
		seen[s] = true
	}
	for _, s := range GetAListOfCurrentUsersPlaylistsToolScopes {
		seen[s] = true
	}
	for _, s := range GetAShowToolScopes {
		seen[s] = true
	}
	for _, s := range GetAShowsEpisodesToolScopes {
		seen[s] = true
	}
	for _, s := range GetAUsersAvailableDevicesToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnAlbumToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnAlbumsTracksToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnArtistToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnArtistsAlbumsToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnAudiobookToolScopes {
		seen[s] = true
	}
	for _, s := range GetAnEpisodeToolScopes {
		seen[s] = true
	}
	for _, s := range GetAudiobookChaptersToolScopes {
		seen[s] = true
	}
	for _, s := range GetCurrentUsersProfileToolScopes {
		seen[s] = true
	}
	for _, s := range GetFollowedToolScopes {
		seen[s] = true
	}
	for _, s := range GetInformationAboutTheUsersCurrentPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range GetPlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range GetPlaylistCoverToolScopes {
		seen[s] = true
	}
	for _, s := range GetPlaylistsItemsToolScopes {
		seen[s] = true
	}
	for _, s := range GetQueueToolScopes {
		seen[s] = true
	}
	for _, s := range GetRecentlyPlayedToolScopes {
		seen[s] = true
	}
	for _, s := range GetTheUsersCurrentlyPlayingTrackToolScopes {
		seen[s] = true
	}
	for _, s := range GetTrackToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedAlbumsToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedAudiobooksToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedEpisodesToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedShowsToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersSavedTracksToolScopes {
		seen[s] = true
	}
	for _, s := range GetUsersTopArtistsAndTracksToolScopes {
		seen[s] = true
	}
	for _, s := range PauseAUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range RemoveItemsPlaylistToolScopes {
		seen[s] = true
	}
	for _, s := range RemoveLibraryItemsToolScopes {
		seen[s] = true
	}
	for _, s := range ReorderOrReplacePlaylistsItemsToolScopes {
		seen[s] = true
	}
	for _, s := range SaveLibraryItemsToolScopes {
		seen[s] = true
	}
	for _, s := range SearchToolScopes {
		seen[s] = true
	}
	for _, s := range SeekToPositionInCurrentlyPlayingTrackToolScopes {
		seen[s] = true
	}
	for _, s := range SetRepeatModeOnUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range SetVolumeForUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range SkipUsersPlaybackToNextTrackToolScopes {
		seen[s] = true
	}
	for _, s := range SkipUsersPlaybackToPreviousTrackToolScopes {
		seen[s] = true
	}
	for _, s := range StartAUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range ToggleShuffleForUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range TransferAUsersPlaybackToolScopes {
		seen[s] = true
	}
	for _, s := range UploadCustomPlaylistCoverToolScopes {
		seen[s] = true
	}
	result := make([]string, 0, len(seen))
	for s := range seen {
		result = append(result, s)
	}
	sort.Strings(result)
	return result
}

// Type conversion helpers for MCP args to Go types.

func toStringSlice(v interface{}) []string {
	arr, ok := v.([]interface{})
	if !ok {
		return nil
	}
	result := make([]string, 0, len(arr))
	for _, item := range arr {
		if s, ok := item.(string); ok {
			result = append(result, s)
		}
	}
	return result
}

func toTypedSlice[T ~string](v interface{}) []T {
	arr, ok := v.([]interface{})
	if !ok {
		return nil
	}
	result := make([]T, 0, len(arr))
	for _, item := range arr {
		if s, ok := item.(string); ok {
			result = append(result, T(s))
		}
	}
	return result
}

func toInt(v interface{}) int {
	switch n := v.(type) {
	case float64:
		return int(n)
	case int:
		return n
	default:
		return 0
	}
}

func toFloat(v interface{}) float64 {
	switch n := v.(type) {
	case float64:
		return n
	case int:
		return float64(n)
	default:
		return 0
	}
}

func toBool(v interface{}) bool {
	b, _ := v.(bool)
	return b
}
