// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetTheUsersCurrentlyPlayingTrackToolScopes lists the OAuth scopes required by the get-the-users-currently-playing-track tool.
var GetTheUsersCurrentlyPlayingTrackToolScopes = []string{"user-read-currently-playing"}

var GetTheUsersCurrentlyPlayingTrackTool = mcp.NewTool("get-the-users-currently-playing-track",
	mcp.WithDescription("Get Currently Playing Track\n\n\nGet the object currently being played on the user's Spotify account.\n"),
	mcp.WithString("market"),
	mcp.WithString("additional_types"),
)

// NewGetTheUsersCurrentlyPlayingTrackHandler creates a handler for the get-the-users-currently-playing-track tool.
func NewGetTheUsersCurrentlyPlayingTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetTheUsersCurrentlyPlayingTrackParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["additional_types"].(string); ok && v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetTheUsersCurrentlyPlayingTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
