// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAShowsEpisodesToolScopes lists the OAuth scopes required by the get-a-shows-episodes tool.
var GetAShowsEpisodesToolScopes = []string{"user-read-playback-position"}

var GetAShowsEpisodesTool = mcp.NewTool("get-a-shows-episodes",
	mcp.WithDescription("Get Show Episodes\n\n\nGet Spotify catalog information about an show’s episodes. Optional parameters can be used to limit the number of episodes returned.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("offset"),
)

// NewGetAShowsEpisodesHandler creates a handler for the get-a-shows-episodes tool.
func NewGetAShowsEpisodesHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		params := &spotify.GetAShowsEpisodesParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["offset"]; ok {
			n := toInt(v)
			params.Offset = &n
		}
		resp, err := client.GetAShowsEpisodesWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
