// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// RemoveLibraryItemsToolScopes lists the OAuth scopes required by the remove-library-items tool.
var RemoveLibraryItemsToolScopes = []string{"user-library-modify", "user-follow-modify", "playlist-modify-public"}

var RemoveLibraryItemsTool = mcp.NewTool("remove-library-items",
	mcp.WithDescription("Remove Items from Library\n\n\nRemove one or more items from the current user's library. Accepts Spotify URIs for tracks, albums, episodes, shows, audiobooks, users, and playlists.\n"),
	mcp.WithString("uris", mcp.Required()),
)

// NewRemoveLibraryItemsHandler creates a handler for the remove-library-items tool.
func NewRemoveLibraryItemsHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.RemoveLibraryItemsParams{}
		params.Uris = args["uris"].(string)
		resp, err := client.RemoveLibraryItemsWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
