// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAnAlbumToolScopes lists the OAuth scopes required by the get-an-album tool.
var GetAnAlbumToolScopes = []string{}

var GetAnAlbumTool = mcp.NewTool("get-an-album",
	mcp.WithDescription("Get Album\n\n\nGet Spotify catalog information for a single album.\n"),
	mcp.WithString("id", mcp.Required()),
	mcp.WithString("market"),
)

// NewGetAnAlbumHandler creates a handler for the get-an-album tool.
func NewGetAnAlbumHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		params := &spotify.GetAnAlbumParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		resp, err := client.GetAnAlbumWithResponse(ctx, id, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
