// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// AddToQueueToolScopes lists the OAuth scopes required by the add-to-queue tool.
var AddToQueueToolScopes = []string{"user-modify-playback-state"}

var AddToQueueTool = mcp.NewTool("add-to-queue",
	mcp.WithDescription("Add Item to Playback Queue\n\n\nAdd an item to be played next in the user's current playback queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("uri", mcp.Required()),
	mcp.WithString("device_id"),
)

// NewAddToQueueHandler creates a handler for the add-to-queue tool.
func NewAddToQueueHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.AddToQueueParams{}
		params.Uri = args["uri"].(string)
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		resp, err := client.AddToQueueWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
