// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAUsersAvailableDevicesToolScopes lists the OAuth scopes required by the get-a-users-available-devices tool.
var GetAUsersAvailableDevicesToolScopes = []string{"user-read-playback-state"}

var GetAUsersAvailableDevicesTool = mcp.NewTool("get-a-users-available-devices",
	mcp.WithDescription("Get Available Devices\n\n\nGet information about a user’s available Spotify Connect devices. Some device models are not supported and will not be listed in the API response.\n"),
)

// NewGetAUsersAvailableDevicesHandler creates a handler for the get-a-users-available-devices tool.
func NewGetAUsersAvailableDevicesHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		resp, err := client.GetAUsersAvailableDevicesWithResponse(ctx)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
