// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetFollowedToolScopes lists the OAuth scopes required by the get-followed tool.
var GetFollowedToolScopes = []string{"user-follow-read"}

var GetFollowedTool = mcp.NewTool("get-followed",
	mcp.WithDescription("Get Followed Artists\n\n\nGet the current user's followed artists.\n"),
	mcp.WithString("type", mcp.Required()),
	mcp.WithString("after"),
	mcp.WithNumber("limit"),
)

// NewGetFollowedHandler creates a handler for the get-followed tool.
func NewGetFollowedHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetFollowedParams{}
		params.Type = spotify.GetFollowedParamsType(args["type"].(string))
		if v, ok := args["after"].(string); ok && v != "" {
			params.After = &v
		}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		resp, err := client.GetFollowedWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
