// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetAnArtistToolScopes lists the OAuth scopes required by the get-an-artist tool.
var GetAnArtistToolScopes = []string{}

var GetAnArtistTool = mcp.NewTool("get-an-artist",
	mcp.WithDescription("Get Artist\n\n\nGet Spotify catalog information for a single artist identified by their unique Spotify ID.\n"),
	mcp.WithString("id", mcp.Required()),
)

// NewGetAnArtistHandler creates a handler for the get-an-artist tool.
func NewGetAnArtistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		id, _ := args["id"].(string)
		resp, err := client.GetAnArtistWithResponse(ctx, id)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
