// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// TransferAUsersPlaybackToolScopes lists the OAuth scopes required by the transfer-a-users-playback tool.
var TransferAUsersPlaybackToolScopes = []string{"user-modify-playback-state"}

var TransferAUsersPlaybackTool = mcp.NewTool("transfer-a-users-playback",
	mcp.WithDescription("Transfer Playback\n\n\nTransfer playback to a new device and optionally begin playback. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
)

// NewTransferAUsersPlaybackHandler creates a handler for the transfer-a-users-playback tool.
func NewTransferAUsersPlaybackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		var body spotify.TransferAUsersPlaybackJSONRequestBody
		resp, err := client.TransferAUsersPlaybackWithResponse(ctx, body)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
