// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// SkipUsersPlaybackToNextTrackToolScopes lists the OAuth scopes required by the skip-users-playback-to-next-track tool.
var SkipUsersPlaybackToNextTrackToolScopes = []string{"user-modify-playback-state"}

var SkipUsersPlaybackToNextTrackTool = mcp.NewTool("skip-users-playback-to-next-track",
	mcp.WithDescription("Skip To Next\n\n\nSkips to next track in the user’s queue. This API only works for users who have Spotify Premium. The order of execution is not guaranteed when you use this API with other Player API endpoints.\n"),
	mcp.WithString("device_id"),
)

// NewSkipUsersPlaybackToNextTrackHandler creates a handler for the skip-users-playback-to-next-track tool.
func NewSkipUsersPlaybackToNextTrackHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.SkipUsersPlaybackToNextTrackParams{}
		if v, ok := args["device_id"].(string); ok && v != "" {
			params.DeviceId = &v
		}
		resp, err := client.SkipUsersPlaybackToNextTrackWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
