// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetPlaylistToolScopes lists the OAuth scopes required by the get-playlist tool.
var GetPlaylistToolScopes = []string{}

var GetPlaylistTool = mcp.NewTool("get-playlist",
	mcp.WithDescription("Get Playlist\n\n\nGet a playlist owned by a Spotify user.\n"),
	mcp.WithString("playlist_id", mcp.Required()),
	mcp.WithString("market"),
	mcp.WithString("fields"),
	mcp.WithString("additional_types"),
)

// NewGetPlaylistHandler creates a handler for the get-playlist tool.
func NewGetPlaylistHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		playlistId, _ := args["playlist_id"].(string)
		params := &spotify.GetPlaylistParams{}
		if v, ok := args["market"].(string); ok && v != "" {
			params.Market = &v
		}
		if v, ok := args["fields"].(string); ok && v != "" {
			params.Fields = &v
		}
		if v, ok := args["additional_types"].(string); ok && v != "" {
			params.AdditionalTypes = &v
		}
		resp, err := client.GetPlaylistWithResponse(ctx, playlistId, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
