// Code generated by cmd/codegen; DO NOT EDIT.

package tools

import (
	"context"
	"fmt"

	"github.com/makesometh-ing/spotify-mcp-go/internal/spotify"
	"github.com/mark3labs/mcp-go/mcp"
)

// GetRecentlyPlayedToolScopes lists the OAuth scopes required by the get-recently-played tool.
var GetRecentlyPlayedToolScopes = []string{"user-read-recently-played"}

var GetRecentlyPlayedTool = mcp.NewTool("get-recently-played",
	mcp.WithDescription("Get Recently Played Tracks\n\n\nGet tracks from the current user's recently played tracks.\n_**Note**: Currently doesn't support podcast episodes._\n"),
	mcp.WithNumber("limit"),
	mcp.WithNumber("after"),
	mcp.WithNumber("before"),
)

// NewGetRecentlyPlayedHandler creates a handler for the get-recently-played tool.
func NewGetRecentlyPlayedHandler(client *spotify.ClientWithResponses) func(context.Context, mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	return func(ctx context.Context, req mcp.CallToolRequest) (*mcp.CallToolResult, error) {
		args := req.GetArguments()
		_ = args
		params := &spotify.GetRecentlyPlayedParams{}
		if v, ok := args["limit"]; ok {
			n := toInt(v)
			params.Limit = &n
		}
		if v, ok := args["after"]; ok {
			n := toInt(v)
			params.After = &n
		}
		if v, ok := args["before"]; ok {
			n := toInt(v)
			params.Before = &n
		}
		resp, err := client.GetRecentlyPlayedWithResponse(ctx, params)
		if err != nil {
			return mcp.NewToolResultError(err.Error()), nil
		}

		if resp.HTTPResponse.StatusCode >= 400 {
			return mcp.NewToolResultError(fmt.Sprintf("Spotify API error %d: %s", resp.HTTPResponse.StatusCode, string(resp.Body))), nil
		}

		return mcp.NewToolResultText(string(resp.Body)), nil
	}
}
